/* Generated by scripts/gen_params.py — DO NOT EDIT BY HAND.
 *
 * module.json is capped at 8 KB by Schwung's loader, so chain_params and the
 * page hierarchy are served dynamically from the DSP via get_param().
 *
 * The pot and enum tables below define storage order for the state blob.
 * Appending is safe; reordering breaks every saved patch.
 */
#ifndef SD606_PARAMS_H
#define SD606_PARAMS_H

typedef enum { SD606_LIN = 0, SD606_EXP = 1 } sd606_curve_t;

typedef struct {
    const char   *key;
    float         min;
    float         max;
    sd606_curve_t curve;
    int           def;      /* default POT position, 0..127 */
} sd606_pot_t;

typedef struct {
    const char *key;
    int         count;      /* number of options */
    int         def;
} sd606_enum_t;

#define SD606_NUM_POTS  64
#define SD606_NUM_ENUMS 12

static const sd606_pot_t g_sd606_pots[SD606_NUM_POTS] = {
    { "bd_tune",    -9.7800f,    14.2200f, SD606_LIN,  40 },
    { "bd_decay",     0.0000f,     1.0000f, SD606_LIN,  24 },
    { "bd_attack",     0.0000f,     1.0000f, SD606_LIN, 120 },
    { "bd_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "bd_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "sd_tune",     0.5000f,     2.0000f, SD606_EXP,  70 },
    { "sd_snappy",     0.0000f,     1.0000f, SD606_LIN,  64 },
    { "sd_tone",     0.5000f,     2.0000f, SD606_EXP,  52 },
    { "sd_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "sd_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "lt_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "lt_decay",     0.0000f,     1.0000f, SD606_LIN, 124 },
    { "lt_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "lt_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "ht_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "ht_decay",     0.0000f,     1.0000f, SD606_LIN, 124 },
    { "ht_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "ht_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "ch_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "ch_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "ch_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "ch_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "oh_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "oh_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "oh_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "oh_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "cy_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "cy_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "cy_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "cy_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "cp_tune",     0.5000f,     2.0000f, SD606_EXP,  64 },
    { "cp_decay",     0.0000f,     1.0000f, SD606_LIN, 102 },
    { "cp_noise",     0.0000f,     1.0000f, SD606_LIN,  64 },
    { "cp_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "cp_level",     0.0000f,     2.0000f, SD606_LIN,  64 },
    { "master_drive",     0.8500f,    12.0000f, SD606_EXP,   8 },
    { "volume",     0.0000f,     1.0000f, SD606_LIN,  76 },
    { "comp",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "vel_depth",     0.0000f,     1.0000f, SD606_LIN, 127 },
    { "bd_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "bd_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "sd_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "sd_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "lt_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "lt_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "ht_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "ht_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "ch_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "ch_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "oh_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "oh_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "cy_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "cy_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "cp_rev",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "cp_dly",     0.0000f,     1.0000f, SD606_LIN,   0 },
    { "rev_decay",     0.2000f,     0.9300f, SD606_LIN,  73 },
    { "rev_tone",     0.0000f,     1.0000f, SD606_LIN,  57 },
    { "rev_hpf",    30.0000f,   800.0000f, SD606_EXP,  62 },
    { "rev_level",     0.0000f,     1.2000f, SD606_LIN,  85 },
    { "dly_fdbk",     0.0000f,     0.8500f, SD606_LIN,  52 },
    { "dly_tone",     0.0000f,     1.0000f, SD606_LIN,  51 },
    { "dly_hpf",    30.0000f,   800.0000f, SD606_EXP,  62 },
    { "dly_level",     0.0000f,     1.2000f, SD606_LIN,  85 },
    { "sd_decay",     0.0000f,     1.0000f, SD606_LIN,  76 },
};

static const sd606_enum_t g_sd606_enums[SD606_NUM_ENUMS] = {
    { "bd_dist_type",  7,  0 },
    { "sd_dist_type",  7,  0 },
    { "lt_dist_type",  7,  0 },
    { "ht_dist_type",  7,  0 },
    { "ch_dist_type",  7,  0 },
    { "hh_choke",  3,  1 },
    { "oh_dist_type",  7,  0 },
    { "cy_dist_type",  7,  0 },
    { "cp_dist_type",  7,  0 },
    { "master_dist",  8,  0 },
    { "note_map",  2,  0 },
    { "dly_time", 13,  7 },
};

#define SD606_CHAIN_PARAMS_LEN 7061
static const char sd606_chain_params_json[] =
    "[{\"key\":\"bd_tune\",\"name\":\"BD Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":40},{\"key\":\"bd_decay\",\"n"
    "ame\":\"BD Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":24},{\"key\":\"bd_attack\",\"name\":\"BD Attack\",\""
    "type\":\"int\",\"min\":0,\"max\":127,\"default\":120,\"viz\":false},{\"key\":\"bd_drive\",\"name\":\"BD Drive\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"bd_dist_type\",\"name\":\"BD Distortion\",\"type\":\"enum\",\"opt"
    "ions\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"bd_level\",\"name\":\"BD "
    "Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"sd_tune\",\"name\":\""
    "SD Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":70},{\"key\":\"sd_snappy\",\"name\":\"SD Snappy\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"sd_tone\",\"name\":\"SD Tone\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"default\":52},{\"key\":\"sd_drive\",\"name\":\"SD Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":8},{\"ke"
    "y\":\"sd_dist_type\",\"name\":\"SD Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\""
    ",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"sd_level\",\"name\":\"SD Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lt_tune\",\"name\":\"LT Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":64},{\"key\":\"lt_decay\",\"name\":\"LT Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":124},{\"key"
    "\":\"lt_drive\",\"name\":\"LT Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"lt_dist_type\",\"na"
    "me\":\"LT Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"def"
    "ault\":0},{\"key\":\"lt_level\",\"name\":\"LT Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kin"
    "d\":\"fader\"}},{\"key\":\"ht_tune\",\"name\":\"HT Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\""
    "ht_decay\",\"name\":\"HT Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":124},{\"key\":\"ht_drive\",\"name\":\""
    "HT Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"ht_dist_type\",\"name\":\"HT Distortion\",\""
    "type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ht_l"
    "evel\",\"name\":\"HT Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\""
    "ch_tune\",\"name\":\"CH Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ch_decay\",\"name\":\"CH "
    "Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":102},{\"key\":\"ch_drive\",\"name\":\"CH Drive\",\"type\":\"int"
    "\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"ch_dist_type\",\"name\":\"CH Distortion\",\"type\":\"enum\",\"options"
    "\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ch_level\",\"name\":\"CH Leve"
    "l\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"hh_choke\",\"name\":\"Cho"
    "ke\",\"type\":\"enum\",\"options\":[\"Off\",\"CH>OH\",\"Mutual\"],\"default\":1},{\"key\":\"oh_tune\",\"name\":\"OH Tune\","
    "\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"oh_decay\",\"name\":\"OH Decay\",\"type\":\"int\",\"min\":"
    "0,\"max\":127,\"default\":102},{\"key\":\"oh_drive\",\"name\":\"OH Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"defau"
    "lt\":8},{\"key\":\"oh_dist_type\",\"name\":\"OH Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"B"
    "FZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"oh_level\",\"name\":\"OH Level\",\"type\":\"int\",\"min\":0,\"m"
    "ax\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cy_tune\",\"name\":\"CY Tune\",\"type\":\"int\",\"min\":0,"
    "\"max\":127,\"default\":64},{\"key\":\"cy_decay\",\"name\":\"CY Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\""
    ":102},{\"key\":\"cy_drive\",\"name\":\"CY Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"cy_dis"
    "t_type\",\"name\":\"CY Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"C"
    "rush\"],\"default\":0},{\"key\":\"cy_level\",\"name\":\"CY Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,"
    "\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cp_tune\",\"name\":\"CP Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":6"
    "4},{\"key\":\"cp_decay\",\"name\":\"CP Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":102},{\"key\":\"cp_nois"
    "e\",\"name\":\"CP Noise\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cp_drive\",\"name\":\"CP Drive"
    "\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":8},{\"key\":\"cp_dist_type\",\"name\":\"CP Distortion\",\"type\":\"e"
    "num\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cp_level\",\"n"
    "ame\":\"CP Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"master_d"
    "ist\",\"name\":\"Master Dist\",\"type\":\"enum\",\"options\":[\"Off\",\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\""
    "Crush\"],\"default\":0},{\"key\":\"master_drive\",\"name\":\"Master Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"def"
    "ault\":8},{\"key\":\"volume\",\"name\":\"Volume\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":76,\"viz\":{\"kind\":\""
    "fader\"}},{\"key\":\"comp\",\"name\":\"Comp\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"vel_depth\","
    "\"name\":\"Velocity\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"note_map\",\"name\":\"Note Map\","
    "\"type\":\"enum\",\"options\":[\"Rack 36\",\"GM\"],\"default\":0},{\"key\":\"bd_rev\",\"name\":\"BD Rev\",\"type\":\"int\",\""
    "min\":0,\"max\":127,\"default\":0},{\"key\":\"bd_dly\",\"name\":\"BD Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"defaul"
    "t\":0},{\"key\":\"sd_rev\",\"name\":\"SD Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"sd_dly\",\"n"
    "ame\":\"SD Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lt_rev\",\"name\":\"LT Rev\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lt_dly\",\"name\":\"LT Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":0},{\"key\":\"ht_rev\",\"name\":\"HT Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ht_dly"
    "\",\"name\":\"HT Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ch_rev\",\"name\":\"CH Rev\",\"type\""
    ":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ch_dly\",\"name\":\"CH Dly\",\"type\":\"int\",\"min\":0,\"max\":127"
    ",\"default\":0},{\"key\":\"oh_rev\",\"name\":\"OH Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"oh"
    "_dly\",\"name\":\"OH Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_rev\",\"name\":\"CY Rev\",\"t"
    "ype\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_dly\",\"name\":\"CY Dly\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":0},{\"key\":\"cp_rev\",\"name\":\"CP Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\""
    ":\"cp_dly\",\"name\":\"CP Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rev_decay\",\"name\":\"REV"
    " Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":73},{\"key\":\"rev_tone\",\"name\":\"REV Tone\",\"type\":\"int"
    "\",\"min\":0,\"max\":127,\"default\":57},{\"key\":\"rev_hpf\",\"name\":\"REV HPF\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":62},{\"key\":\"rev_level\",\"name\":\"REV Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":85,\"viz\""
    ":{\"kind\":\"fader\"}},{\"key\":\"dly_time\",\"name\":\"DLY Time\",\"type\":\"enum\",\"options\":[\"1/32\",\"1/16T\",\"1/16"
    "\",\"1/8T\",\"1/16.\",\"1/8\",\"1/4T\",\"1/8.\",\"1/4\",\"1/2T\",\"1/4.\",\"1/2\",\"1/2.\"],\"default\":7},{\"key\":\"dly_fdbk"
    "\",\"name\":\"DLY Fdbk\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":52},{\"key\":\"dly_tone\",\"name\":\"DLY Tone\""
    ",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":51},{\"key\":\"dly_hpf\",\"name\":\"DLY HPF\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":62},{\"key\":\"dly_level\",\"name\":\"DLY Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"defau"
    "lt\":85,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"sd_decay\",\"name\":\"SD Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":76},{\"key\":\"ui_focus\",\"name\":\"Focus\",\"type\":\"int\",\"min\":0,\"max\":8,\"default\":0},{\"key\":\"mutes"
    "\",\"name\":\"Mutes\",\"type\":\"int\",\"min\":0,\"max\":255,\"default\":0}]";

#define SD606_UI_PAGES_LEN 4555
static const char sd606_ui_pages_json[] =
    "{\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd_tune\",\"bd_decay\",\"bd_attack\",\"bd_drive\",\"bd_dist_ty"
    "pe\",\"bd_level\",\"bd_rev\",\"bd_dly\"],\"params\":[{\"key\":\"bd_tune\",\"label\":\"Tune\"},{\"key\":\"bd_decay\",\"labe"
    "l\":\"Decay\"},{\"key\":\"bd_attack\",\"label\":\"Attack\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":\"bd_dist_"
    "type\",\"label\":\"Distortion\"},{\"key\":\"bd_level\",\"label\":\"Level\"},{\"key\":\"bd_rev\",\"label\":\"Rev\"},{\"key\""
    ":\"bd_dly\",\"label\":\"Dly\"}],\"note\":36,\"role\":\"kick\"},\"sd\":{\"name\":\"Snare\",\"knobs\":[\"sd_tune\",\"sd_snapp"
    "y\",\"sd_decay\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"sd_rev\",\"sd_dly\"],\"params\":[{\"key\":\"sd_tune\",\"la"
    "bel\":\"Tune\"},{\"key\":\"sd_snappy\",\"label\":\"Snappy\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key\":\"sd_driv"
    "e\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"sd_level\",\"label\":\"Level\"},{"
    "\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\":\"Dly\"}],\"note\":37,\"role\":\"snare\"},\"lt\":{\"name\""
    ":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\",\"lt_rev\",\"lt_dly\"],\"pa"
    "rams\":[{\"key\":\"lt_tune\",\"label\":\"Tune\"},{\"key\":\"lt_decay\",\"label\":\"Decay\"},{\"key\":\"lt_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"lt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lt_level\",\"label\":\"Level\"},{\"key\":\"lt_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"lt_dly\",\"label\":\"Dly\"}],\"note\":38,\"role\":\"tom\"},\"ht\":{\"name\":\"Hi Tom\",\"k"
    "nobs\":[\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht_dist_type\",\"ht_level\",\"ht_rev\",\"ht_dly\"],\"params\":[{\"key\""
    ":\"ht_tune\",\"label\":\"Tune\"},{\"key\":\"ht_decay\",\"label\":\"Decay\"},{\"key\":\"ht_drive\",\"label\":\"Drive\"},{\"k"
    "ey\":\"ht_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ht_level\",\"label\":\"Level\"},{\"key\":\"ht_rev\",\"label\":"
    "\"Rev\"},{\"key\":\"ht_dly\",\"label\":\"Dly\"}],\"note\":39,\"role\":\"tom\"},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"c"
    "h_tune\",\"ch_decay\",\"ch_drive\",\"ch_dist_type\",\"ch_level\",\"hh_choke\",\"ch_rev\",\"ch_dly\"],\"params\":[{\"ke"
    "y\":\"ch_tune\",\"label\":\"Tune\"},{\"key\":\"ch_decay\",\"label\":\"Decay\"},{\"key\":\"ch_drive\",\"label\":\"Drive\"},{"
    "\"key\":\"ch_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ch_level\",\"label\":\"Level\"},{\"key\":\"hh_choke\",\"lab"
    "el\":\"Choke\"},{\"key\":\"ch_rev\",\"label\":\"Rev\"},{\"key\":\"ch_dly\",\"label\":\"Dly\"}],\"note\":40,\"role\":\"hat\"},"
    "\"oh\":{\"name\":\"Open Hat\",\"knobs\":[\"oh_tune\",\"oh_decay\",\"oh_drive\",\"oh_dist_type\",\"oh_level\",\"oh_rev\","
    "\"oh_dly\"],\"params\":[{\"key\":\"oh_tune\",\"label\":\"Tune\"},{\"key\":\"oh_decay\",\"label\":\"Decay\"},{\"key\":\"oh_d"
    "rive\",\"label\":\"Drive\"},{\"key\":\"oh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"oh_level\",\"label\":\"Level\""
    "},{\"key\":\"oh_rev\",\"label\":\"Rev\"},{\"key\":\"oh_dly\",\"label\":\"Dly\"}],\"note\":41,\"role\":\"hat\"},\"cy\":{\"name"
    "\":\"Cymbal\",\"knobs\":[\"cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\",\"cy_rev\",\"cy_dly\"],\"pa"
    "rams\":[{\"key\":\"cy_tune\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\"key\":\"cy_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"cy_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"label\":\"Level\"},{\"key\":\"cy_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"cy_dly\",\"label\":\"Dly\"}],\"note\":42,\"role\":\"cymbal\"},\"cp\":{\"name\":\"Clap\",\""
    "knobs\":[\"cp_tune\",\"cp_decay\",\"cp_noise\",\"cp_drive\",\"cp_dist_type\",\"cp_level\",\"cp_rev\",\"cp_dly\"],\"par"
    "ams\":[{\"key\":\"cp_tune\",\"label\":\"Tune\"},{\"key\":\"cp_decay\",\"label\":\"Decay\"},{\"key\":\"cp_noise\",\"label\":"
    "\"Noise\"},{\"key\":\"cp_drive\",\"label\":\"Drive\"},{\"key\":\"cp_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cp_l"
    "evel\",\"label\":\"Level\"},{\"key\":\"cp_rev\",\"label\":\"Rev\"},{\"key\":\"cp_dly\",\"label\":\"Dly\"}],\"note\":43,\"rol"
    "e\":\"clap\"},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_decay\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{"
    "\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_tone\",\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"}"
    ",{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"name\":\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_ton"
    "e\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_time\",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdb"
    "k\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly_hpf\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Le"
    "vel\"}]},\"root\":{\"name\":\"6W6\",\"knobs\":[\"master_dist\",\"master_drive\",\"comp\",\"volume\",\"vel_depth\"],\"par"
    "ams\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"lt\",\"label\":\"Low T"
    "om\"},{\"level\":\"ht\",\"label\":\"Hi Tom\"},{\"level\":\"ch\",\"label\":\"Closed Hat\"},{\"level\":\"oh\",\"label\":\"Open"
    " Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\"cp\",\"label\":\"Clap\"},{\"level\":\"rev\",\"label\":\"Reverb\""
    "},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{\"key\":\"master_drive\","
    "\"label\":\"Master Drive\"},{\"key\":\"volume\",\"label\":\"Volume\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"vel_"
    "depth\",\"label\":\"Velocity\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\"note_map\",\"label\":\"Note Map\"}]"
    "}},\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\"}";

/* The same hierarchy with GENERAL MIDI notes. The note map is switchable at
   runtime, so one static declaration would be wrong half the time and a host
   would lay every pad out in the wrong place with nothing to say why.
   get_param picks between the two -- a pointer choice, nothing built on the
   audio thread. Costs one extra copy of the JSON in flash. */
#define SD606_UI_PAGES_GM_LEN 4555
static const char sd606_ui_pages_gm_json[] =
    "{\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd_tune\",\"bd_decay\",\"bd_attack\",\"bd_drive\",\"bd_dist_ty"
    "pe\",\"bd_level\",\"bd_rev\",\"bd_dly\"],\"params\":[{\"key\":\"bd_tune\",\"label\":\"Tune\"},{\"key\":\"bd_decay\",\"labe"
    "l\":\"Decay\"},{\"key\":\"bd_attack\",\"label\":\"Attack\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":\"bd_dist_"
    "type\",\"label\":\"Distortion\"},{\"key\":\"bd_level\",\"label\":\"Level\"},{\"key\":\"bd_rev\",\"label\":\"Rev\"},{\"key\""
    ":\"bd_dly\",\"label\":\"Dly\"}],\"note\":36,\"role\":\"kick\"},\"sd\":{\"name\":\"Snare\",\"knobs\":[\"sd_tune\",\"sd_snapp"
    "y\",\"sd_decay\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"sd_rev\",\"sd_dly\"],\"params\":[{\"key\":\"sd_tune\",\"la"
    "bel\":\"Tune\"},{\"key\":\"sd_snappy\",\"label\":\"Snappy\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key\":\"sd_driv"
    "e\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"sd_level\",\"label\":\"Level\"},{"
    "\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\":\"Dly\"}],\"note\":38,\"role\":\"snare\"},\"lt\":{\"name\""
    ":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\",\"lt_rev\",\"lt_dly\"],\"pa"
    "rams\":[{\"key\":\"lt_tune\",\"label\":\"Tune\"},{\"key\":\"lt_decay\",\"label\":\"Decay\"},{\"key\":\"lt_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"lt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lt_level\",\"label\":\"Level\"},{\"key\":\"lt_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"lt_dly\",\"label\":\"Dly\"}],\"note\":41,\"role\":\"tom\"},\"ht\":{\"name\":\"Hi Tom\",\"k"
    "nobs\":[\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht_dist_type\",\"ht_level\",\"ht_rev\",\"ht_dly\"],\"params\":[{\"key\""
    ":\"ht_tune\",\"label\":\"Tune\"},{\"key\":\"ht_decay\",\"label\":\"Decay\"},{\"key\":\"ht_drive\",\"label\":\"Drive\"},{\"k"
    "ey\":\"ht_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ht_level\",\"label\":\"Level\"},{\"key\":\"ht_rev\",\"label\":"
    "\"Rev\"},{\"key\":\"ht_dly\",\"label\":\"Dly\"}],\"note\":48,\"role\":\"tom\"},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"c"
    "h_tune\",\"ch_decay\",\"ch_drive\",\"ch_dist_type\",\"ch_level\",\"hh_choke\",\"ch_rev\",\"ch_dly\"],\"params\":[{\"ke"
    "y\":\"ch_tune\",\"label\":\"Tune\"},{\"key\":\"ch_decay\",\"label\":\"Decay\"},{\"key\":\"ch_drive\",\"label\":\"Drive\"},{"
    "\"key\":\"ch_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ch_level\",\"label\":\"Level\"},{\"key\":\"hh_choke\",\"lab"
    "el\":\"Choke\"},{\"key\":\"ch_rev\",\"label\":\"Rev\"},{\"key\":\"ch_dly\",\"label\":\"Dly\"}],\"note\":42,\"role\":\"hat\"},"
    "\"oh\":{\"name\":\"Open Hat\",\"knobs\":[\"oh_tune\",\"oh_decay\",\"oh_drive\",\"oh_dist_type\",\"oh_level\",\"oh_rev\","
    "\"oh_dly\"],\"params\":[{\"key\":\"oh_tune\",\"label\":\"Tune\"},{\"key\":\"oh_decay\",\"label\":\"Decay\"},{\"key\":\"oh_d"
    "rive\",\"label\":\"Drive\"},{\"key\":\"oh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"oh_level\",\"label\":\"Level\""
    "},{\"key\":\"oh_rev\",\"label\":\"Rev\"},{\"key\":\"oh_dly\",\"label\":\"Dly\"}],\"note\":46,\"role\":\"hat\"},\"cy\":{\"name"
    "\":\"Cymbal\",\"knobs\":[\"cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\",\"cy_rev\",\"cy_dly\"],\"pa"
    "rams\":[{\"key\":\"cy_tune\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\"key\":\"cy_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"cy_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"label\":\"Level\"},{\"key\":\"cy_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"cy_dly\",\"label\":\"Dly\"}],\"note\":49,\"role\":\"cymbal\"},\"cp\":{\"name\":\"Clap\",\""
    "knobs\":[\"cp_tune\",\"cp_decay\",\"cp_noise\",\"cp_drive\",\"cp_dist_type\",\"cp_level\",\"cp_rev\",\"cp_dly\"],\"par"
    "ams\":[{\"key\":\"cp_tune\",\"label\":\"Tune\"},{\"key\":\"cp_decay\",\"label\":\"Decay\"},{\"key\":\"cp_noise\",\"label\":"
    "\"Noise\"},{\"key\":\"cp_drive\",\"label\":\"Drive\"},{\"key\":\"cp_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cp_l"
    "evel\",\"label\":\"Level\"},{\"key\":\"cp_rev\",\"label\":\"Rev\"},{\"key\":\"cp_dly\",\"label\":\"Dly\"}],\"note\":39,\"rol"
    "e\":\"clap\"},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_decay\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{"
    "\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_tone\",\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"}"
    ",{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"name\":\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_ton"
    "e\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_time\",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdb"
    "k\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly_hpf\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Le"
    "vel\"}]},\"root\":{\"name\":\"6W6\",\"knobs\":[\"master_dist\",\"master_drive\",\"comp\",\"volume\",\"vel_depth\"],\"par"
    "ams\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"lt\",\"label\":\"Low T"
    "om\"},{\"level\":\"ht\",\"label\":\"Hi Tom\"},{\"level\":\"ch\",\"label\":\"Closed Hat\"},{\"level\":\"oh\",\"label\":\"Open"
    " Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\"cp\",\"label\":\"Clap\"},{\"level\":\"rev\",\"label\":\"Reverb\""
    "},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{\"key\":\"master_drive\","
    "\"label\":\"Master Drive\"},{\"key\":\"volume\",\"label\":\"Volume\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"vel_"
    "depth\",\"label\":\"Velocity\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\"note_map\",\"label\":\"Note Map\"}]"
    "}},\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\"}";

#endif /* SD606_PARAMS_H */
