/* Generated by scripts/gen_params.py — DO NOT EDIT BY HAND.
 *
 * module.json is capped at 8 KB by Schwung's loader, so chain_params and the
 * page hierarchy are served dynamically from the DSP via get_param().
 *
 * The pot and enum tables below define storage order for the state blob.
 * Appending is safe; reordering breaks every saved patch.
 */
#ifndef CR78_PARAMS_H
#define CR78_PARAMS_H

typedef enum { CR78_LIN = 0, CR78_EXP = 1 } cr78_curve_t;

typedef struct {
    const char   *key;
    float         min;
    float         max;
    cr78_curve_t  curve;
    int           def;      /* default POT position, 0..127 */
} cr78_pot_t;

typedef struct {
    const char *key;
    int         count;      /* number of options */
    int         def;
} cr78_enum_t;

#define CR78_NUM_POTS  96
#define CR78_NUM_ENUMS 22

static const cr78_pot_t g_cr78_pots[CR78_NUM_POTS] = {
    { "bd_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "bd_decay",     0.0300f,     1.0000f, CR78_EXP,  44 },
    { "bd_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "bd_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "sd_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "sd_decay",     0.0200f,     0.6000f, CR78_EXP,  41 },
    { "sd_snappy",     0.0000f,     1.0000f, CR78_LIN,  64 },
    { "sd_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "sd_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "rs_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "rs_decay",     0.0020f,     0.0800f, CR78_EXP,  32 },
    { "rs_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "rs_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "hh_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "hh_decay",     0.0100f,     0.6000f, CR78_EXP,  56 },
    { "hh_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "hh_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "cy_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "cy_decay",     0.0500f,     3.0000f, CR78_EXP,  60 },
    { "cy_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "cy_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "ma_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "ma_decay",     0.0050f,     0.6000f, CR78_EXP,  37 },
    { "ma_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "ma_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "cl_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "cl_decay",     0.0050f,     0.2000f, CR78_EXP,  44 },
    { "cl_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "cl_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "hb_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "hb_decay",     0.0100f,     0.4000f, CR78_EXP,  48 },
    { "hb_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "hb_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "lb_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "lb_decay",     0.0100f,     0.4000f, CR78_EXP,  48 },
    { "lb_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "lb_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "lc_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "lc_decay",     0.0300f,     1.2000f, CR78_EXP,  55 },
    { "lc_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "lc_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "cb_tune",   -12.0000f,    12.0000f, CR78_LIN,  64 },
    { "cb_decay",     0.0200f,     0.8000f, CR78_EXP,  38 },
    { "cb_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "cb_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "tb_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "tb_decay",     0.0130f,     1.5000f, CR78_EXP,  76 },
    { "tb_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "tb_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "gu_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "gu_decay",     0.0500f,     1.0000f, CR78_EXP,  59 },
    { "gu_rate",     0.0000f,     1.0000f, CR78_LIN,  64 },
    { "gu_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "gu_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "mb_tune",     0.5000f,     2.0000f, CR78_EXP,  64 },
    { "mb_decay",     0.0100f,     0.5000f, CR78_EXP,  52 },
    { "mb_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "mb_level",     0.0000f,     2.0000f, CR78_LIN,  64 },
    { "master_drive",     0.0000f,    10.0000f, CR78_LIN,   0 },
    { "comp",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "volume",     0.0000f,     1.0000f, CR78_LIN, 100 },
    { "vel_depth",     0.0000f,     1.0000f, CR78_LIN, 127 },
    { "sd_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "sd_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "rs_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "rs_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "hh_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "hh_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cy_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cy_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "ma_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "ma_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cl_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cl_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "hb_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "hb_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "lb_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "lb_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "lc_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "lc_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cb_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "cb_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "tb_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "tb_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "gu_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "gu_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "mb_rev",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "mb_dly",     0.0000f,     1.0000f, CR78_LIN,   0 },
    { "rev_decay",     0.2000f,     0.9300f, CR78_LIN,  73 },
    { "rev_tone",     0.0000f,     1.0000f, CR78_LIN,  57 },
    { "rev_hpf",    30.0000f,   800.0000f, CR78_EXP,  62 },
    { "rev_level",     0.0000f,     1.2000f, CR78_LIN,  85 },
    { "dly_fdbk",     0.0000f,     0.8500f, CR78_LIN,  52 },
    { "dly_tone",     0.0000f,     1.0000f, CR78_LIN,  51 },
    { "dly_hpf",    30.0000f,   800.0000f, CR78_EXP,  62 },
    { "dly_level",     0.0000f,     1.2000f, CR78_LIN,  85 },
};

static const cr78_enum_t g_cr78_enums[CR78_NUM_ENUMS] = {
    { "bd_dist_type",  7,  0 },
    { "sd_dist_type",  7,  0 },
    { "rs_dist_type",  7,  0 },
    { "hh_dist_type",  7,  0 },
    { "cy_dist_type",  7,  0 },
    { "ma_dist_type",  7,  0 },
    { "cl_dist_type",  7,  0 },
    { "hb_dist_type",  7,  0 },
    { "lb_dist_type",  7,  0 },
    { "lc_dist_type",  7,  0 },
    { "cb_dist_type",  7,  0 },
    { "tb_dist_type",  7,  0 },
    { "gu_dist_type",  7,  0 },
    { "mb_dist_type",  7,  0 },
    { "master_dist",  8,  0 },
    { "note_map",  2,  0 },
    { "hat_choke",  3,  0 },
    { "dly_time", 13,  7 },
    { "rhy_mode",  2,  0 },
    { "rhy_ab",  2,  0 },
    { "rhy_style", 17, 11 },
    { "rhy_style2", 18,  0 },
};

#define CR78_CHAIN_PARAMS_LEN 11107
static const char cr78_chain_params_json[] =
    "[{\"key\":\"bd_tune\",\"name\":\"BD Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"bd_decay\",\"n"
    "ame\":\"BD Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":44},{\"key\":\"bd_drive\",\"name\":\"BD Drive\",\"ty"
    "pe\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"bd_dist_type\",\"name\":\"BD Distortion\",\"type\":\"enum\","
    "\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"bd_level\",\"name\":"
    "\"BD Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"sd_tune\",\"nam"
    "e\":\"SD Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"sd_decay\",\"name\":\"SD Decay\",\"type\""
    ":\"int\",\"min\":0,\"max\":127,\"default\":41},{\"key\":\"sd_snappy\",\"name\":\"SD Snappy\",\"type\":\"int\",\"min\":0,\"m"
    "ax\":127,\"default\":64},{\"key\":\"sd_drive\",\"name\":\"SD Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0"
    "},{\"key\":\"sd_dist_type\",\"name\":\"SD Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\""
    "PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"sd_level\",\"name\":\"SD Level\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"rs_tune\",\"name\":\"RS Tune\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":64},{\"key\":\"rs_decay\",\"name\":\"RS Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":32},"
    "{\"key\":\"rs_drive\",\"name\":\"RS Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rs_dist_type"
    "\",\"name\":\"RS Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"]"
    ",\"default\":0},{\"key\":\"rs_level\",\"name\":\"RS Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":"
    "{\"kind\":\"fader\"}},{\"key\":\"hh_tune\",\"name\":\"HH Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"k"
    "ey\":\"hh_decay\",\"name\":\"HH Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":56},{\"key\":\"hh_drive\",\"nam"
    "e\":\"HH Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hh_dist_type\",\"name\":\"HH Distortio"
    "n\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\""
    "hh_level\",\"name\":\"HH Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"ke"
    "y\":\"cy_tune\",\"name\":\"CY Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cy_decay\",\"name\":"
    "\"CY Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":60},{\"key\":\"cy_drive\",\"name\":\"CY Drive\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_dist_type\",\"name\":\"CY Distortion\",\"type\":\"enum\",\"opti"
    "ons\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cy_level\",\"name\":\"CY L"
    "evel\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ma_tune\",\"name\":\"M"
    " Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ma_decay\",\"name\":\"M Decay\",\"type\":\"int\","
    "\"min\":0,\"max\":127,\"default\":37},{\"key\":\"ma_drive\",\"name\":\"M Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":0},{\"key\":\"ma_dist_type\",\"name\":\"M Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\""
    ",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ma_level\",\"name\":\"M Level\",\"type\":\"int\",\"min\":0,"
    "\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cl_tune\",\"name\":\"C Tune\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":64},{\"key\":\"cl_decay\",\"name\":\"C Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\""
    ":44},{\"key\":\"cl_drive\",\"name\":\"C Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_dist_"
    "type\",\"name\":\"C Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crus"
    "h\"],\"default\":0},{\"key\":\"cl_level\",\"name\":\"C Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz"
    "\":{\"kind\":\"fader\"}},{\"key\":\"hb_tune\",\"name\":\"HB Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{"
    "\"key\":\"hb_decay\",\"name\":\"HB Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":48},{\"key\":\"hb_drive\",\"n"
    "ame\":\"HB Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hb_dist_type\",\"name\":\"HB Distort"
    "ion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\""
    ":\"hb_level\",\"name\":\"HB Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\""
    "key\":\"lb_tune\",\"name\":\"LB Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"lb_decay\",\"name"
    "\":\"LB Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":48},{\"key\":\"lb_drive\",\"name\":\"LB Drive\",\"type\""
    ":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lb_dist_type\",\"name\":\"LB Distortion\",\"type\":\"enum\",\"op"
    "tions\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"lb_level\",\"name\":\"LB"
    " Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lc_tune\",\"name\":"
    "\"LC Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"lc_decay\",\"name\":\"LC Decay\",\"type\":\"i"
    "nt\",\"min\":0,\"max\":127,\"default\":55},{\"key\":\"lc_drive\",\"name\":\"LC Drive\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"default\":0},{\"key\":\"lc_dist_type\",\"name\":\"LC Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\""
    ",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"lc_level\",\"name\":\"LC Level\",\"type\":\"int\",\""
    "min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cb_tune\",\"name\":\"CB Tune\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cb_decay\",\"name\":\"CB Decay\",\"type\":\"int\",\"min\":0,\"max\":127,"
    "\"default\":38},{\"key\":\"cb_drive\",\"name\":\"CB Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\""
    ":\"cb_dist_type\",\"name\":\"CB Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\""
    "Fold\",\"Crush\"],\"default\":0},{\"key\":\"cb_level\",\"name\":\"CB Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"tb_tune\",\"name\":\"TB Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":64},{\"key\":\"tb_decay\",\"name\":\"TB Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":76},{\"key\":\""
    "tb_drive\",\"name\":\"TB Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"tb_dist_type\",\"name\""
    ":\"TB Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"defaul"
    "t\":0},{\"key\":\"tb_level\",\"name\":\"TB Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":"
    "\"fader\"}},{\"key\":\"gu_tune\",\"name\":\"G Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"gu_d"
    "ecay\",\"name\":\"G Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":59},{\"key\":\"gu_rate\",\"name\":\"G Rate\""
    ",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"gu_drive\",\"name\":\"G Drive\",\"type\":\"int\",\"min\":"
    "0,\"max\":127,\"default\":0},{\"key\":\"gu_dist_type\",\"name\":\"G Distortion\",\"type\":\"enum\",\"options\":[\"Diode"
    "\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"gu_level\",\"name\":\"G Level\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"mb_tune\",\"name\":\"MB Tune\",\"type"
    "\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"mb_decay\",\"name\":\"MB Decay\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":52},{\"key\":\"mb_drive\",\"name\":\"MB Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0}"
    ",{\"key\":\"mb_dist_type\",\"name\":\"MB Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"P"
    "DIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"mb_level\",\"name\":\"MB Level\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"master_dist\",\"name\":\"Master Dist\",\"type\":\"enum\",\"opti"
    "ons\":[\"Off\",\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"master_drive\",\"n"
    "ame\":\"Master Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"comp\",\"name\":\"Comp\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"volume\",\"name\":\"Volume\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":100,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"vel_depth\",\"name\":\"Velocity\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":127},{\"key\":\"note_map\",\"name\":\"Note Map\",\"type\":\"enum\",\"options\":[\"Rack 36\",\"GM\"],\"de"
    "fault\":0},{\"key\":\"hat_choke\",\"name\":\"Choke\",\"type\":\"enum\",\"options\":[\"Off\",\"MA/TB\",\"All3\"],\"default\""
    ":0},{\"key\":\"sd_rev\",\"name\":\"SD Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"sd_dly\",\"nam"
    "e\":\"SD Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rs_rev\",\"name\":\"RS Rev\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rs_dly\",\"name\":\"RS Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":0},{\"key\":\"hh_rev\",\"name\":\"HH Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hh_dly\","
    "\"name\":\"HH Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_rev\",\"name\":\"CY Rev\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_dly\",\"name\":\"CY Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":0},{\"key\":\"ma_rev\",\"name\":\"M Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ma_dl"
    "y\",\"name\":\"M Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_rev\",\"name\":\"C Rev\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_dly\",\"name\":\"C Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":0},{\"key\":\"hb_rev\",\"name\":\"HB Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hb_d"
    "ly\",\"name\":\"HB Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lb_rev\",\"name\":\"LB Rev\",\"typ"
    "e\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lb_dly\",\"name\":\"LB Dly\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"default\":0},{\"key\":\"lc_rev\",\"name\":\"LC Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\""
    "lc_dly\",\"name\":\"LC Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cb_rev\",\"name\":\"CB Rev\","
    "\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cb_dly\",\"name\":\"CB Dly\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":0},{\"key\":\"tb_rev\",\"name\":\"TB Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"ke"
    "y\":\"tb_dly\",\"name\":\"TB Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"gu_rev\",\"name\":\"G Re"
    "v\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"gu_dly\",\"name\":\"G Dly\",\"type\":\"int\",\"min\":0,\""
    "max\":127,\"default\":0},{\"key\":\"mb_rev\",\"name\":\"MB Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\""
    "key\":\"mb_dly\",\"name\":\"MB Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rev_decay\",\"name\":"
    "\"REV Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":73},{\"key\":\"rev_tone\",\"name\":\"REV Tone\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":57},{\"key\":\"rev_hpf\",\"name\":\"REV HPF\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"default\":62},{\"key\":\"rev_level\",\"name\":\"REV Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":85,\""
    "viz\":{\"kind\":\"fader\"}},{\"key\":\"dly_time\",\"name\":\"DLY Time\",\"type\":\"enum\",\"options\":[\"1/32\",\"1/16T\",\""
    "1/16\",\"1/8T\",\"1/16.\",\"1/8\",\"1/4T\",\"1/8.\",\"1/4\",\"1/2T\",\"1/4.\",\"1/2\",\"1/2.\"],\"default\":7},{\"key\":\"dly_"
    "fdbk\",\"name\":\"DLY Fdbk\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":52},{\"key\":\"dly_tone\",\"name\":\"DLY T"
    "one\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":51},{\"key\":\"dly_hpf\",\"name\":\"DLY HPF\",\"type\":\"int\",\"mi"
    "n\":0,\"max\":127,\"default\":62},{\"key\":\"dly_level\",\"name\":\"DLY Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":85,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"rhy_mode\",\"name\":\"RHY Mode\",\"type\":\"enum\",\"options\":[\"Off"
    "\",\"Play\"],\"default\":0},{\"key\":\"rhy_ab\",\"name\":\"RHY A/B\",\"type\":\"enum\",\"options\":[\"A\",\"B\"],\"default\":"
    "0},{\"key\":\"rhy_style\",\"name\":\"RHY Rhythm 1\",\"type\":\"enum\",\"options\":[\"Waltz\",\"Shufl\",\"SloRck\",\"Swing"
    "\",\"FoxTng\",\"Boogie\",\"Enka\",\"Bossa\",\"Samba\",\"MamCha\",\"BegRhu\",\"Rock1\",\"Rock2\",\"Rock3\",\"Rock4\",\"Disco1"
    "\",\"Disco2\"],\"default\":11},{\"key\":\"rhy_style2\",\"name\":\"RHY Rhythm 2\",\"type\":\"enum\",\"options\":[\"Off\",\""
    "Waltz\",\"Shufl\",\"SloRck\",\"Swing\",\"FoxTng\",\"Boogie\",\"Enka\",\"Bossa\",\"Samba\",\"MamCha\",\"BegRhu\",\"Rock1\",\""
    "Rock2\",\"Rock3\",\"Rock4\",\"Disco1\",\"Disco2\"],\"default\":0},{\"key\":\"ui_focus\",\"name\":\"Focus\",\"type\":\"int\""
    ",\"min\":0,\"max\":16,\"default\":0},{\"key\":\"mutes\",\"name\":\"Mutes\",\"type\":\"int\",\"min\":0,\"max\":16383,\"defau"
    "lt\":0}]";

#define CR78_UI_PAGES_LEN 7208
static const char cr78_ui_pages_json[] =
    "{\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\",\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"note\":36,\"r"
    "ole\":\"drum\",\"knobs\":[\"bd_tune\",\"bd_decay\",\"bd_drive\",\"bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd"
    "_tune\",\"label\":\"Tune\"},{\"key\":\"bd_decay\",\"label\":\"Decay\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":"
    "\"bd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"bd_level\",\"label\":\"Level\"}]},\"sd\":{\"name\":\"Snare\",\"note"
    "\":37,\"role\":\"drum\",\"knobs\":[\"sd_tune\",\"sd_decay\",\"sd_snappy\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"s"
    "d_rev\",\"sd_dly\"],\"params\":[{\"key\":\"sd_tune\",\"label\":\"Tune\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key"
    "\":\"sd_snappy\",\"label\":\"Snappy\"},{\"key\":\"sd_drive\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Di"
    "stortion\"},{\"key\":\"sd_level\",\"label\":\"Level\"},{\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\""
    ":\"Dly\"}]},\"rs\":{\"name\":\"Rim Shot\",\"note\":38,\"role\":\"drum\",\"knobs\":[\"rs_tune\",\"rs_decay\",\"rs_drive\",\""
    "rs_dist_type\",\"rs_level\",\"rs_rev\",\"rs_dly\"],\"params\":[{\"key\":\"rs_tune\",\"label\":\"Tune\"},{\"key\":\"rs_de"
    "cay\",\"label\":\"Decay\"},{\"key\":\"rs_drive\",\"label\":\"Drive\"},{\"key\":\"rs_dist_type\",\"label\":\"Distortion\"}"
    ",{\"key\":\"rs_level\",\"label\":\"Level\"},{\"key\":\"rs_rev\",\"label\":\"Rev\"},{\"key\":\"rs_dly\",\"label\":\"Dly\"}]},"
    "\"hh\":{\"name\":\"Hi-Hat\",\"note\":39,\"role\":\"drum\",\"knobs\":[\"hh_tune\",\"hh_decay\",\"hh_drive\",\"hh_dist_type"
    "\",\"hh_level\",\"hh_rev\",\"hh_dly\"],\"params\":[{\"key\":\"hh_tune\",\"label\":\"Tune\"},{\"key\":\"hh_decay\",\"label\""
    ":\"Decay\"},{\"key\":\"hh_drive\",\"label\":\"Drive\"},{\"key\":\"hh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"hh_"
    "level\",\"label\":\"Level\"},{\"key\":\"hh_rev\",\"label\":\"Rev\"},{\"key\":\"hh_dly\",\"label\":\"Dly\"}]},\"cy\":{\"name\""
    ":\"Cymbal\",\"note\":40,\"role\":\"drum\",\"knobs\":[\"cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\""
    ",\"cy_rev\",\"cy_dly\"],\"params\":[{\"key\":\"cy_tune\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\""
    "key\":\"cy_drive\",\"label\":\"Drive\"},{\"key\":\"cy_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"labe"
    "l\":\"Level\"},{\"key\":\"cy_rev\",\"label\":\"Rev\"},{\"key\":\"cy_dly\",\"label\":\"Dly\"}]},\"ma\":{\"name\":\"Maracas\",\""
    "note\":41,\"role\":\"drum\",\"knobs\":[\"ma_tune\",\"ma_decay\",\"ma_drive\",\"ma_dist_type\",\"ma_level\",\"ma_rev\",\""
    "ma_dly\"],\"params\":[{\"key\":\"ma_tune\",\"label\":\"Tune\"},{\"key\":\"ma_decay\",\"label\":\"Decay\"},{\"key\":\"ma_dr"
    "ive\",\"label\":\"Drive\"},{\"key\":\"ma_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ma_level\",\"label\":\"Level\"}"
    ",{\"key\":\"ma_rev\",\"label\":\"Rev\"},{\"key\":\"ma_dly\",\"label\":\"Dly\"}]},\"cl\":{\"name\":\"Claves\",\"note\":42,\"ro"
    "le\":\"drum\",\"knobs\":[\"cl_tune\",\"cl_decay\",\"cl_drive\",\"cl_dist_type\",\"cl_level\",\"cl_rev\",\"cl_dly\"],\"pa"
    "rams\":[{\"key\":\"cl_tune\",\"label\":\"Tune\"},{\"key\":\"cl_decay\",\"label\":\"Decay\"},{\"key\":\"cl_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"cl_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cl_level\",\"label\":\"Level\"},{\"key\":\"cl_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"cl_dly\",\"label\":\"Dly\"}]},\"hb\":{\"name\":\"Hi Bongo\",\"note\":43,\"role\":\"drum\""
    ",\"knobs\":[\"hb_tune\",\"hb_decay\",\"hb_drive\",\"hb_dist_type\",\"hb_level\",\"hb_rev\",\"hb_dly\"],\"params\":[{\"k"
    "ey\":\"hb_tune\",\"label\":\"Tune\"},{\"key\":\"hb_decay\",\"label\":\"Decay\"},{\"key\":\"hb_drive\",\"label\":\"Drive\"},"
    "{\"key\":\"hb_dist_type\",\"label\":\"Distortion\"},{\"key\":\"hb_level\",\"label\":\"Level\"},{\"key\":\"hb_rev\",\"labe"
    "l\":\"Rev\"},{\"key\":\"hb_dly\",\"label\":\"Dly\"}]},\"lb\":{\"name\":\"Low Bongo\",\"note\":44,\"role\":\"drum\",\"knobs\":"
    "[\"lb_tune\",\"lb_decay\",\"lb_drive\",\"lb_dist_type\",\"lb_level\",\"lb_rev\",\"lb_dly\"],\"params\":[{\"key\":\"lb_t"
    "une\",\"label\":\"Tune\"},{\"key\":\"lb_decay\",\"label\":\"Decay\"},{\"key\":\"lb_drive\",\"label\":\"Drive\"},{\"key\":\"l"
    "b_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lb_level\",\"label\":\"Level\"},{\"key\":\"lb_rev\",\"label\":\"Rev\"}"
    ",{\"key\":\"lb_dly\",\"label\":\"Dly\"}]},\"lc\":{\"name\":\"Low Conga\",\"note\":45,\"role\":\"drum\",\"knobs\":[\"lc_tune"
    "\",\"lc_decay\",\"lc_drive\",\"lc_dist_type\",\"lc_level\",\"lc_rev\",\"lc_dly\"],\"params\":[{\"key\":\"lc_tune\",\"lab"
    "el\":\"Tune\"},{\"key\":\"lc_decay\",\"label\":\"Decay\"},{\"key\":\"lc_drive\",\"label\":\"Drive\"},{\"key\":\"lc_dist_ty"
    "pe\",\"label\":\"Distortion\"},{\"key\":\"lc_level\",\"label\":\"Level\"},{\"key\":\"lc_rev\",\"label\":\"Rev\"},{\"key\":\""
    "lc_dly\",\"label\":\"Dly\"}]},\"cb\":{\"name\":\"Cowbell\",\"note\":46,\"role\":\"drum\",\"knobs\":[\"cb_tune\",\"cb_decay"
    "\",\"cb_drive\",\"cb_dist_type\",\"cb_level\",\"cb_rev\",\"cb_dly\"],\"params\":[{\"key\":\"cb_tune\",\"label\":\"Tune\"}"
    ",{\"key\":\"cb_decay\",\"label\":\"Decay\"},{\"key\":\"cb_drive\",\"label\":\"Drive\"},{\"key\":\"cb_dist_type\",\"label\""
    ":\"Distortion\"},{\"key\":\"cb_level\",\"label\":\"Level\"},{\"key\":\"cb_rev\",\"label\":\"Rev\"},{\"key\":\"cb_dly\",\"la"
    "bel\":\"Dly\"}]},\"tb\":{\"name\":\"Tambourine\",\"note\":47,\"role\":\"drum\",\"knobs\":[\"tb_tune\",\"tb_decay\",\"tb_dr"
    "ive\",\"tb_dist_type\",\"tb_level\",\"tb_rev\",\"tb_dly\"],\"params\":[{\"key\":\"tb_tune\",\"label\":\"Tune\"},{\"key\":"
    "\"tb_decay\",\"label\":\"Decay\"},{\"key\":\"tb_drive\",\"label\":\"Drive\"},{\"key\":\"tb_dist_type\",\"label\":\"Distor"
    "tion\"},{\"key\":\"tb_level\",\"label\":\"Level\"},{\"key\":\"tb_rev\",\"label\":\"Rev\"},{\"key\":\"tb_dly\",\"label\":\"Dl"
    "y\"}]},\"gu\":{\"name\":\"Guiro\",\"note\":48,\"role\":\"drum\",\"knobs\":[\"gu_tune\",\"gu_decay\",\"gu_rate\",\"gu_drive"
    "\",\"gu_dist_type\",\"gu_level\",\"gu_rev\",\"gu_dly\"],\"params\":[{\"key\":\"gu_tune\",\"label\":\"Tune\"},{\"key\":\"gu"
    "_decay\",\"label\":\"Decay\"},{\"key\":\"gu_rate\",\"label\":\"Rate\"},{\"key\":\"gu_drive\",\"label\":\"Drive\"},{\"key\":"
    "\"gu_dist_type\",\"label\":\"Distortion\"},{\"key\":\"gu_level\",\"label\":\"Level\"},{\"key\":\"gu_rev\",\"label\":\"Rev"
    "\"},{\"key\":\"gu_dly\",\"label\":\"Dly\"}]},\"mb\":{\"name\":\"Metal Beat\",\"note\":49,\"role\":\"drum\",\"knobs\":[\"mb_t"
    "une\",\"mb_decay\",\"mb_drive\",\"mb_dist_type\",\"mb_level\",\"mb_rev\",\"mb_dly\"],\"params\":[{\"key\":\"mb_tune\",\""
    "label\":\"Tune\"},{\"key\":\"mb_decay\",\"label\":\"Decay\"},{\"key\":\"mb_drive\",\"label\":\"Drive\"},{\"key\":\"mb_dist"
    "_type\",\"label\":\"Distortion\"},{\"key\":\"mb_level\",\"label\":\"Level\"},{\"key\":\"mb_rev\",\"label\":\"Rev\"},{\"key"
    "\":\"mb_dly\",\"label\":\"Dly\"}]},\"rhy\":{\"name\":\"Rhythm\",\"knobs\":[\"rhy_mode\",\"rhy_ab\",\"rhy_style\",\"rhy_sty"
    "le2\"],\"params\":[{\"key\":\"rhy_mode\",\"label\":\"Mode\"},{\"key\":\"rhy_ab\",\"label\":\"A/B\"},{\"key\":\"rhy_style\","
    "\"label\":\"Rhythm 1\"},{\"key\":\"rhy_style2\",\"label\":\"Rhythm 2\"}]},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_d"
    "ecay\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_to"
    "ne\",\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"},{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"na"
    "me\":\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_tone\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_t"
    "ime\",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdbk\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly"
    "_hpf\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Level\"}]},\"root\":{\"name\":\"CW-78\",\"knobs\":[\"master_d"
    "ist\",\"master_drive\",\"comp\",\"volume\",\"vel_depth\",\"hat_choke\"],\"params\":[{\"level\":\"bd\",\"label\":\"Bass D"
    "rum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"rs\",\"label\":\"Rim Shot\"},{\"level\":\"hh\",\"label\":\"Hi-Hat"
    "\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\"ma\",\"label\":\"Maracas\"},{\"level\":\"cl\",\"label\":\"Claves\"},"
    "{\"level\":\"hb\",\"label\":\"Hi Bongo\"},{\"level\":\"lb\",\"label\":\"Low Bongo\"},{\"level\":\"lc\",\"label\":\"Low Cong"
    "a\"},{\"level\":\"cb\",\"label\":\"Cowbell\"},{\"level\":\"tb\",\"label\":\"Tambourine\"},{\"level\":\"gu\",\"label\":\"Guir"
    "o\"},{\"level\":\"mb\",\"label\":\"Metal Beat\"},{\"level\":\"rhy\",\"label\":\"Rhythm\"},{\"level\":\"rev\",\"label\":\"Rev"
    "erb\"},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{\"key\":\"master_dri"
    "ve\",\"label\":\"Master Drive\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"volume\",\"label\":\"Volume\"},{\"key\":\""
    "vel_depth\",\"label\":\"Velocity\"},{\"key\":\"note_map\",\"label\":\"Note Map\"},{\"key\":\"hat_choke\",\"label\":\"Cho"
    "ke\"}]}}}";

/* The same hierarchy with General MIDI notes, for when note_map is GM. The
 * plugin picks between the two in get_param on "ui_pages". */
#define CR78_UI_PAGES_GM_LEN 7208
static const char cr78_ui_pages_gm_json[] =
    "{\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\",\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"note\":36,\"r"
    "ole\":\"drum\",\"knobs\":[\"bd_tune\",\"bd_decay\",\"bd_drive\",\"bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd"
    "_tune\",\"label\":\"Tune\"},{\"key\":\"bd_decay\",\"label\":\"Decay\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":"
    "\"bd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"bd_level\",\"label\":\"Level\"}]},\"sd\":{\"name\":\"Snare\",\"note"
    "\":38,\"role\":\"drum\",\"knobs\":[\"sd_tune\",\"sd_decay\",\"sd_snappy\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"s"
    "d_rev\",\"sd_dly\"],\"params\":[{\"key\":\"sd_tune\",\"label\":\"Tune\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key"
    "\":\"sd_snappy\",\"label\":\"Snappy\"},{\"key\":\"sd_drive\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Di"
    "stortion\"},{\"key\":\"sd_level\",\"label\":\"Level\"},{\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\""
    ":\"Dly\"}]},\"rs\":{\"name\":\"Rim Shot\",\"note\":37,\"role\":\"drum\",\"knobs\":[\"rs_tune\",\"rs_decay\",\"rs_drive\",\""
    "rs_dist_type\",\"rs_level\",\"rs_rev\",\"rs_dly\"],\"params\":[{\"key\":\"rs_tune\",\"label\":\"Tune\"},{\"key\":\"rs_de"
    "cay\",\"label\":\"Decay\"},{\"key\":\"rs_drive\",\"label\":\"Drive\"},{\"key\":\"rs_dist_type\",\"label\":\"Distortion\"}"
    ",{\"key\":\"rs_level\",\"label\":\"Level\"},{\"key\":\"rs_rev\",\"label\":\"Rev\"},{\"key\":\"rs_dly\",\"label\":\"Dly\"}]},"
    "\"hh\":{\"name\":\"Hi-Hat\",\"note\":42,\"role\":\"drum\",\"knobs\":[\"hh_tune\",\"hh_decay\",\"hh_drive\",\"hh_dist_type"
    "\",\"hh_level\",\"hh_rev\",\"hh_dly\"],\"params\":[{\"key\":\"hh_tune\",\"label\":\"Tune\"},{\"key\":\"hh_decay\",\"label\""
    ":\"Decay\"},{\"key\":\"hh_drive\",\"label\":\"Drive\"},{\"key\":\"hh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"hh_"
    "level\",\"label\":\"Level\"},{\"key\":\"hh_rev\",\"label\":\"Rev\"},{\"key\":\"hh_dly\",\"label\":\"Dly\"}]},\"cy\":{\"name\""
    ":\"Cymbal\",\"note\":49,\"role\":\"drum\",\"knobs\":[\"cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\""
    ",\"cy_rev\",\"cy_dly\"],\"params\":[{\"key\":\"cy_tune\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\""
    "key\":\"cy_drive\",\"label\":\"Drive\"},{\"key\":\"cy_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"labe"
    "l\":\"Level\"},{\"key\":\"cy_rev\",\"label\":\"Rev\"},{\"key\":\"cy_dly\",\"label\":\"Dly\"}]},\"ma\":{\"name\":\"Maracas\",\""
    "note\":70,\"role\":\"drum\",\"knobs\":[\"ma_tune\",\"ma_decay\",\"ma_drive\",\"ma_dist_type\",\"ma_level\",\"ma_rev\",\""
    "ma_dly\"],\"params\":[{\"key\":\"ma_tune\",\"label\":\"Tune\"},{\"key\":\"ma_decay\",\"label\":\"Decay\"},{\"key\":\"ma_dr"
    "ive\",\"label\":\"Drive\"},{\"key\":\"ma_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ma_level\",\"label\":\"Level\"}"
    ",{\"key\":\"ma_rev\",\"label\":\"Rev\"},{\"key\":\"ma_dly\",\"label\":\"Dly\"}]},\"cl\":{\"name\":\"Claves\",\"note\":75,\"ro"
    "le\":\"drum\",\"knobs\":[\"cl_tune\",\"cl_decay\",\"cl_drive\",\"cl_dist_type\",\"cl_level\",\"cl_rev\",\"cl_dly\"],\"pa"
    "rams\":[{\"key\":\"cl_tune\",\"label\":\"Tune\"},{\"key\":\"cl_decay\",\"label\":\"Decay\"},{\"key\":\"cl_drive\",\"label\""
    ":\"Drive\"},{\"key\":\"cl_dist_type\",\"label\":\"Distortion\"},{\"key\":\"cl_level\",\"label\":\"Level\"},{\"key\":\"cl_"
    "rev\",\"label\":\"Rev\"},{\"key\":\"cl_dly\",\"label\":\"Dly\"}]},\"hb\":{\"name\":\"Hi Bongo\",\"note\":60,\"role\":\"drum\""
    ",\"knobs\":[\"hb_tune\",\"hb_decay\",\"hb_drive\",\"hb_dist_type\",\"hb_level\",\"hb_rev\",\"hb_dly\"],\"params\":[{\"k"
    "ey\":\"hb_tune\",\"label\":\"Tune\"},{\"key\":\"hb_decay\",\"label\":\"Decay\"},{\"key\":\"hb_drive\",\"label\":\"Drive\"},"
    "{\"key\":\"hb_dist_type\",\"label\":\"Distortion\"},{\"key\":\"hb_level\",\"label\":\"Level\"},{\"key\":\"hb_rev\",\"labe"
    "l\":\"Rev\"},{\"key\":\"hb_dly\",\"label\":\"Dly\"}]},\"lb\":{\"name\":\"Low Bongo\",\"note\":61,\"role\":\"drum\",\"knobs\":"
    "[\"lb_tune\",\"lb_decay\",\"lb_drive\",\"lb_dist_type\",\"lb_level\",\"lb_rev\",\"lb_dly\"],\"params\":[{\"key\":\"lb_t"
    "une\",\"label\":\"Tune\"},{\"key\":\"lb_decay\",\"label\":\"Decay\"},{\"key\":\"lb_drive\",\"label\":\"Drive\"},{\"key\":\"l"
    "b_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lb_level\",\"label\":\"Level\"},{\"key\":\"lb_rev\",\"label\":\"Rev\"}"
    ",{\"key\":\"lb_dly\",\"label\":\"Dly\"}]},\"lc\":{\"name\":\"Low Conga\",\"note\":64,\"role\":\"drum\",\"knobs\":[\"lc_tune"
    "\",\"lc_decay\",\"lc_drive\",\"lc_dist_type\",\"lc_level\",\"lc_rev\",\"lc_dly\"],\"params\":[{\"key\":\"lc_tune\",\"lab"
    "el\":\"Tune\"},{\"key\":\"lc_decay\",\"label\":\"Decay\"},{\"key\":\"lc_drive\",\"label\":\"Drive\"},{\"key\":\"lc_dist_ty"
    "pe\",\"label\":\"Distortion\"},{\"key\":\"lc_level\",\"label\":\"Level\"},{\"key\":\"lc_rev\",\"label\":\"Rev\"},{\"key\":\""
    "lc_dly\",\"label\":\"Dly\"}]},\"cb\":{\"name\":\"Cowbell\",\"note\":56,\"role\":\"drum\",\"knobs\":[\"cb_tune\",\"cb_decay"
    "\",\"cb_drive\",\"cb_dist_type\",\"cb_level\",\"cb_rev\",\"cb_dly\"],\"params\":[{\"key\":\"cb_tune\",\"label\":\"Tune\"}"
    ",{\"key\":\"cb_decay\",\"label\":\"Decay\"},{\"key\":\"cb_drive\",\"label\":\"Drive\"},{\"key\":\"cb_dist_type\",\"label\""
    ":\"Distortion\"},{\"key\":\"cb_level\",\"label\":\"Level\"},{\"key\":\"cb_rev\",\"label\":\"Rev\"},{\"key\":\"cb_dly\",\"la"
    "bel\":\"Dly\"}]},\"tb\":{\"name\":\"Tambourine\",\"note\":54,\"role\":\"drum\",\"knobs\":[\"tb_tune\",\"tb_decay\",\"tb_dr"
    "ive\",\"tb_dist_type\",\"tb_level\",\"tb_rev\",\"tb_dly\"],\"params\":[{\"key\":\"tb_tune\",\"label\":\"Tune\"},{\"key\":"
    "\"tb_decay\",\"label\":\"Decay\"},{\"key\":\"tb_drive\",\"label\":\"Drive\"},{\"key\":\"tb_dist_type\",\"label\":\"Distor"
    "tion\"},{\"key\":\"tb_level\",\"label\":\"Level\"},{\"key\":\"tb_rev\",\"label\":\"Rev\"},{\"key\":\"tb_dly\",\"label\":\"Dl"
    "y\"}]},\"gu\":{\"name\":\"Guiro\",\"note\":73,\"role\":\"drum\",\"knobs\":[\"gu_tune\",\"gu_decay\",\"gu_rate\",\"gu_drive"
    "\",\"gu_dist_type\",\"gu_level\",\"gu_rev\",\"gu_dly\"],\"params\":[{\"key\":\"gu_tune\",\"label\":\"Tune\"},{\"key\":\"gu"
    "_decay\",\"label\":\"Decay\"},{\"key\":\"gu_rate\",\"label\":\"Rate\"},{\"key\":\"gu_drive\",\"label\":\"Drive\"},{\"key\":"
    "\"gu_dist_type\",\"label\":\"Distortion\"},{\"key\":\"gu_level\",\"label\":\"Level\"},{\"key\":\"gu_rev\",\"label\":\"Rev"
    "\"},{\"key\":\"gu_dly\",\"label\":\"Dly\"}]},\"mb\":{\"name\":\"Metal Beat\",\"note\":80,\"role\":\"drum\",\"knobs\":[\"mb_t"
    "une\",\"mb_decay\",\"mb_drive\",\"mb_dist_type\",\"mb_level\",\"mb_rev\",\"mb_dly\"],\"params\":[{\"key\":\"mb_tune\",\""
    "label\":\"Tune\"},{\"key\":\"mb_decay\",\"label\":\"Decay\"},{\"key\":\"mb_drive\",\"label\":\"Drive\"},{\"key\":\"mb_dist"
    "_type\",\"label\":\"Distortion\"},{\"key\":\"mb_level\",\"label\":\"Level\"},{\"key\":\"mb_rev\",\"label\":\"Rev\"},{\"key"
    "\":\"mb_dly\",\"label\":\"Dly\"}]},\"rhy\":{\"name\":\"Rhythm\",\"knobs\":[\"rhy_mode\",\"rhy_ab\",\"rhy_style\",\"rhy_sty"
    "le2\"],\"params\":[{\"key\":\"rhy_mode\",\"label\":\"Mode\"},{\"key\":\"rhy_ab\",\"label\":\"A/B\"},{\"key\":\"rhy_style\","
    "\"label\":\"Rhythm 1\"},{\"key\":\"rhy_style2\",\"label\":\"Rhythm 2\"}]},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_d"
    "ecay\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_to"
    "ne\",\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"},{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"na"
    "me\":\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_tone\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_t"
    "ime\",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdbk\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly"
    "_hpf\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Level\"}]},\"root\":{\"name\":\"CW-78\",\"knobs\":[\"master_d"
    "ist\",\"master_drive\",\"comp\",\"volume\",\"vel_depth\",\"hat_choke\"],\"params\":[{\"level\":\"bd\",\"label\":\"Bass D"
    "rum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"rs\",\"label\":\"Rim Shot\"},{\"level\":\"hh\",\"label\":\"Hi-Hat"
    "\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\"ma\",\"label\":\"Maracas\"},{\"level\":\"cl\",\"label\":\"Claves\"},"
    "{\"level\":\"hb\",\"label\":\"Hi Bongo\"},{\"level\":\"lb\",\"label\":\"Low Bongo\"},{\"level\":\"lc\",\"label\":\"Low Cong"
    "a\"},{\"level\":\"cb\",\"label\":\"Cowbell\"},{\"level\":\"tb\",\"label\":\"Tambourine\"},{\"level\":\"gu\",\"label\":\"Guir"
    "o\"},{\"level\":\"mb\",\"label\":\"Metal Beat\"},{\"level\":\"rhy\",\"label\":\"Rhythm\"},{\"level\":\"rev\",\"label\":\"Rev"
    "erb\"},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{\"key\":\"master_dri"
    "ve\",\"label\":\"Master Drive\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"volume\",\"label\":\"Volume\"},{\"key\":\""
    "vel_depth\",\"label\":\"Velocity\"},{\"key\":\"note_map\",\"label\":\"Note Map\"},{\"key\":\"hat_choke\",\"label\":\"Cho"
    "ke\"}]}}}";

#endif /* CR78_PARAMS_H */
