#!/usr/bin/env python3
"""TR-MPC "full" skin: every slot a module that reskins itself to the drum port its voice comes from.

Writes ports/trkit/layouts/full.conf (+ full_preview.conf: one voice page, full_fx_preview.conf: the FX page, rnd_preview.conf: the
randomise page) and the artwork in ports/trkit/images/. `bash tools/gen_skins_docker.sh gen_trmpc_full.py` runs it where fontTools is
available (the drum ports' lettering is outlined from ../mpc-vst/Assets/fonts); build_ci.sh does that for you.

Everything visual is the drum ports' own: faceplates are cropped from gen_drum_skins.plate_svg, the knobs are the ports' built filmstrips
(copied from _build/<kit>/skin), colours and lettering come from gen_drum_skins.STYLES / text_path.

Each slot has a derived "kit" parameter (sNN_fam: 0 6W6, 1 8W8, 2 CW-78, 3 9W9, 4 the 9W9 kick, which has three extra controls and so a
denser layout); every kit-specific piece of the slot is a `when=sNN_fam:<n>` line. The voice menu doubles as the module title.
"""
import glob
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_drum_skins as drum            # noqa: E402
import gen_trmpc_skin as base            # noqa: E402

PORT, ROOT = base.PORT, base.ROOT
W, H, Y_OFF, TOP, BOT = base.W, base.H, base.Y_OFF, base.TOP, base.BOT

FAMILIES = ["6w6", "8w8", "cw78", "9w9"]              # = the order of the kit parameter
FAMILY_NAME = {"6w6": "6W6", "8w8": "8W8", "cw78": "CW-78", "9w9": "9W9"}
NINE_BD = 38                                          # flat index of the 9W9 kick (6 + 8 + 16 + 14 voices before it... see gen_trkit_params)
PX0, PW, PPITCH = 10, 310, 316                        # panel x of the first module, panel width, pitch (4 panels fill 1280 px)
CELL_X = (78, 232)                                    # knob cell centres, relative to the panel
REG = dict(row0=220, pitch=99, r=20)                 # five rows of two
DENSE = dict(row0=205, pitch=86, r=16)                # six rows of two (the 9W9 kick)
CELLS = {"dist": (0, 0), "level": (1, 0), "tune": (0, 1), "decay": (1, 1), "x1": (0, 2), "x2": (1, 2),
         "drive": (0, 3), "pan": (1, 3), "rev": (0, 4), "dly": (1, 4)}
CELLS_DENSE = {"dist": (0, 0), "level": (1, 0), "tune": (0, 1), "decay": (1, 1), "x1": (0, 2), "x2": (1, 2), "x3": (0, 3),
               "drive": (1, 3), "pan": (0, 4), "rev": (0, 5), "dly": (1, 5)}
ORANGE = "f2561d"                                     # the TR-MPC lettering on the utility pages

_GROUP_COLOURS = {   # voice-menu colours per kit: heading fill / text, option fill / text (from each kit's panel theme)
    "6w6": ("b9bbb4", "1a1d24", "d9dad4", "1a1d24"),
    "8w8": ("141414", "f1f827", "202020", "ffffff"),
    "cw78": ("121316", "ff5a00", "1c1d21", "ecd5aa"),
    "9w9": ("e6e2d6", "4b5566", "e6e2d6", "ef6c1f"),
}
GROUPS = ",".join("%s TR-%s:%d:%s" % (t[0], t[1], n, ":".join(_GROUP_COLOURS[k])) for t, n, k in (
    (("6W6", "606"), 8, "6w6"), (("8W8", "808"), 16, "8w8"), (("CW-78", "CR-78"), 14, "cw78"), (("9W9", "909"), 11, "9w9")))
GROUPS = GROUPS.replace("CW-78 TR-CR-78", "CW-78 CR-78")


def _theme(kit):
    return dict(kv.split("=") for kv in drum.STYLES[kit]["theme"].split())


FAM = {k: dict(ink=_theme(k)["ink"], dim=_theme(k)["ink_dim"], dist=_theme(k)["accent"], field=_theme(k)["lcd"],
               title=drum.STYLES[k]["title_color"]) for k in drum.STYLES}
FAM["8w8"]["title"] = "1a1a1a"            # on its cream pill
for _k in ("6w6", "9w9"):                 # light panels: the knob names use the dim ink, which was too pale to read
    FAM[_k]["dim"] = FAM[_k]["ink"]

# the ports' own knob filmstrips (built by their skin builds, tools/build_all.sh: _build/<kit>/skin/*/Plugin Skins/sh_knob_r26_<look>.png);
# <look> is the built-in look id: 77dc8a3f = metal, 61370ca5 = cap. Copied into ports/trkit/images/ so they are vendored.
KNOB_STRIPS = {"6w6": ("6w6", "77dc8a3f"), "8w8": ("8w8", "61370ca5"), "8w8_level": ("8w8", "77dc8a3f"),
               "cw78": ("cw78", "61370ca5"), "9w9": ("9w9", "61370ca5")}

THEME = base.THEME.replace("theme_ink=e8e9ec", "theme_ink=f1eee4").replace("theme_ink_dim=9a9ea8", "theme_ink_dim=c9c4b3") \
    .replace("theme_bg=17181b", "theme_bg=1f1f1f").replace("theme_knob_dot=5ec2b7", "theme_knob_dot=f1eee4") \
    .replace("theme_knob_face=34363c", "theme_knob_face=1b1b1d") \
    .replace("art_css=skin.css\nknob_look=cap", "art_css=skin_full.css\nknob_look=cap\nlabel_scale=0.9\nscale_names=1")

CSS = """/* TR-MPC skin (full): generated by tools/gen_trmpc_full.py. Faceplates are the drum ports' own plate art (images/panel_*.svg);
 * lettering is outlined into the art, the knobs are the ports' filmstrips (images/knob_*.png). */
:root { --label-size: 14px; --sheen: 0.06; }
.frame-border { fill: none; stroke: none; }
.frame-rule { stroke: none; }
.knob-face, .look-metal, .look-body, .look-cap-ring, .look-fader { filter: none; }
.look-cap-ring { fill: #0e0e0f; stroke: #000; stroke-opacity: 0.6; } .look-cap-top { fill: #232326; } .look-line { stroke: #f1eee4; }
.look-led { stroke: #000; stroke-opacity: 0.5; }
"""


def vendor_knobs():
    for name, (kit, look) in KNOB_STRIPS.items():
        dst = os.path.join(PORT, "images", "knob_%s.png" % name)
        hits = glob.glob(os.path.join(ROOT, "_build", kit, "skin", "*", "Plugin Skins", "sh_knob_r26_%s.png" % look))
        if hits:
            shutil.copyfile(hits[0], dst)
        elif not os.path.isfile(dst):
            raise SystemExit("no knob strip for %s: run tools/build_all.sh %s first" % (name, kit))


def crop_svg(svg, x, y, w, h):
    """The same drawing, showing only the box x,y,w,h (the svg's viewBox is moved; the drawing is untouched)."""
    return re.sub(r'viewBox="[^"]*" width="\d+" height="\d+"', 'viewBox="%g %g %g %g" width="%g" height="%g"' % (x, y, w, h, w, h), svg, count=1)


def _caption(f, cx, cy, text):
    return ('<text x="%g" y="%g" font-family="Titillium Web" font-weight="600" font-size="14" letter-spacing="1.2" fill="#%s">%s</text>'
            % (cx - 65, cy - TOP - 28, f["ink"], text))


def faceplate(kit, popups=(), title="", arrow=True, watermark=True, pill=True, screws=("tl", "tr", "bl", "br")):
    """One module's faceplate: the drum port's own panel art (gen_drum_skins.plate_svg cropped to one panel), the port's title baked in
    when given, a drawn field (and caption) for each popup (cx, cy, caption), a title-menu arrow, and the kit's name as a faint
    vertical watermark."""
    f = FAM[kit]
    svg = drum.plate_svg(kit, 1, [title], name="TR-MPC")
    if kit == "8w8" and not title:   # the 808's title pill: sized for a voice name, or left out
        svg = re.sub(r'<rect [^>]*height="26" rx="13" fill="#f3efdc"/>', ('<rect x="%g" y="%d" width="206" height="26" rx="13" fill="#f3efdc"/>' % (
            drum.panel_xs(1)[0] + 26, TOP - Y_OFF + 7)) if pill else "", svg)
    svg = crop_svg(svg, drum.panel_xs(1)[0], TOP - Y_OFF, PW, BOT - TOP)
    add = []
    if watermark:
        st = drum.STYLES[kit]
        g, wd = drum.text_path(st["logo"][1], FAMILY_NAME[kit], 0, 0, 46, st["logo_color"], opacity=0.14, anchor="start")
        add.append('<g transform="translate(30 %d) rotate(-90)">%s</g>' % (BOT - TOP - 26, g))   # up the bottom-left edge
    for cx, cy, caption in popups:
        add.append(_caption(f, cx, cy, caption))
        add.append('<rect x="%g" y="%g" width="130" height="44" fill="#%s"/>' % (cx - 65, cy - TOP - 22, f["field"]))
        add.append('<path d="M%g %g L%g %g L%g %g Z" fill="#%s"/>' % (cx + 35, cy - TOP - 4, cx + 51, cy - TOP - 4, cx + 43, cy - TOP + 5, f["dist"]))
    if arrow:    # the title menu's arrow
        add.append('<path d="M%d 15 L%d 15 L%d 23 Z" fill="#%s"/>' % (PW - 50, PW - 34, PW - 42, f["title"]))
    corners = {"tl": (14, 14), "tr": (PW - 14, 14), "bl": (14, BOT - TOP - 14), "br": (PW - 14, BOT - TOP - 14)}
    add += [drum.screw(*corners[c]) for c in screws]
    ox, oy = drum.panel_xs(1)[0], TOP - Y_OFF   # the cropped drawing keeps the plate's page coordinates: move ours to the panel
    return svg.replace("</svg>", '<g transform="translate(%g %g)">%s</g></svg>' % (ox, oy, "".join(add)))


def blank_plate():
    """An empty module: the 808 panel with screws and the TR-MPC name outlined in orange."""
    svg = faceplate("8w8", watermark=False, pill=False, arrow=False, screws=())
    st = drum.STYLES["8w8"]
    nm, _ = drum.text_path("Eurostile", "TR-MPC", PW / 2, 270, 40, ORANGE, opacity=0.6, anchor="middle")
    tg, _ = drum.text_path(st["fonts"][1], "MODULAR DRUM RACK", PW / 2, 312, 11, "a8a49a", spacing=2, opacity=0.6, anchor="middle", bold=0.02)
    scr = "".join(drum.screw(x, y) for x, y in ((14, 14), (PW - 14, 14), (14, BOT - TOP - 14), (PW - 14, BOT - TOP - 14)))
    ox, oy = drum.panel_xs(1)[0], TOP - Y_OFF
    return svg.replace("</svg>", '<g transform="translate(%g %g)">%s%s%s</g></svg>' % (ox, oy, nm, tg, scr))


def chassis_svg(logo_colour):
    """The page behind the modules: the 808's satin-black chassis, with the page header's lettering outlined into the art."""
    hy = drum.HEADER_CY - Y_OFF
    logo, _ = drum.text_path("Eurostile", "TR-MPC", 24, hy, 30, logo_colour)
    tag, _ = drum.text_path("Helvetica", "16-SLOT MODULAR DRUM RACK - ANY VOICE FROM 6W6 / 8W8 / CW-78 / 9W9", 24 + 3 * 15 * 6 + 40, hy + 4, 13,
                            "c9c4b3", spacing=2, bold=0.02)
    d = [drum.DEFS, drum.base("8w8"), logo, tag,
         '<rect x="0" y="%d" width="%d" height="2" fill="#%s" fill-opacity="0.7"/>' % (drum.HEAD_Y1 - Y_OFF - 3, W, logo_colour)]
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d">%s</svg>\n' % (W, H, W, H, "".join(d))



STEP_GREY = "c9c4b3"                                  # lit slot keys (the unlit face is this darkened)


def _mix(c, k):
    return "".join("%02x" % int(int(c[i:i + 2], 16) * k) for i in (0, 2, 4))


def button_svg(w, h, text, colour, lit, size):
    """A lit or unlit key: rounded plate in the key's colour (dark when off, glowing when on), the lettering outlined on it."""
    face = colour if lit else _mix(colour, 0.30)
    ink = "1a1a1a" if lit else "8f8b80"
    t, _ = drum.text_path("Eurostile", text, w / 2, h / 2 - size * 0.08, size, ink, anchor="middle")
    d = ['<rect x="2" y="2" width="%d" height="%d" rx="10" fill="#0b0b0c"/>' % (w - 4, h - 4),
         '<rect x="6" y="5" width="%d" height="%d" rx="8" fill="#%s"/>' % (w - 12, h - 12, face),
         '<rect x="6" y="5" width="%d" height="%d" rx="8" fill="url(#g)" opacity="%s"/>' % (w - 12, (h - 12) // 2, "0.35" if lit else "0.12")]
    if lit:
        d.append('<rect x="3" y="2" width="%d" height="%d" rx="10" fill="none" stroke="#%s" stroke-opacity="0.55" stroke-width="2"/>' % (w - 6, h - 4, colour))
    defs = '<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient></defs>'
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d">%s%s%s</svg>\n' % (w, h, w, h, defs, "".join(d), t)


def write_button(name, w, h, text, colour, size):
    """images/<name>_off.svg and _on.svg; returns the layout attributes for them."""
    for lit in (0, 1):
        _write("images/%s_%s.svg" % (name, "on" if lit else "off"), button_svg(w, h, text, colour, lit, size))
    return "img=images/%s_off.svg img_on=images/%s_on.svg w=%d h=%d" % (name, name, w, h)


def caption_on(svg, px, text, cy, size=11):
    """Outlined small lettering centred on a panel (panel coordinates: x from the panel's left edge, y in page pixels)."""
    t, _ = drum.text_path("Helvetica", text, PW / 2, cy - TOP, size, "a8a49a", spacing=1.5, anchor="middle", bold=0.02)
    ox, oy = drum.panel_xs(1)[0], TOP - Y_OFF
    return svg.replace("</svg>", '<g transform="translate(%g %g)">%s</g></svg>' % (ox, oy, t))


def _cell(px, geo, cells, name):
    col, row = cells[name]
    return px + CELL_X[col], geo["row0"] + row * geo["pitch"]


def _write(path, text):
    open(os.path.join(PORT, path), "w", newline="\n").write(text)


def extra_lines(out, k, px):
    """Each voice's own extra controls, a knob per voice that has one at that position, shown only while that voice is selected."""
    ex = base.extras_by_slot_knob()
    for n in range(3):
        for flat, kind, label in ex[n]:
            dense = flat == NINE_BD
            cells, geo = (CELLS_DENSE, DENSE) if dense else (CELLS, REG)
            if "x%d" % (n + 1) not in cells:
                continue
            kit = base.KIT_OF[flat]
            cx, cy = _cell(px, geo, cells, "x%d" % (n + 1))
            out.append('knob cx=%d cy=%d r=%d label="%s" key=%s%s strip=images/knob_%s.png ink=%s ink_dim=%s when=%ssrc:%d' % (
                cx, cy, geo["r"], label, k, kind, kit, FAM[kit]["ink"], FAM[kit]["dim"], k, flat))


def voice_page(out, page):
    slots = list(range(page * 4 + 1, page * 4 + 5))
    out += ["", "[tab S%d - S%d]" % (slots[0], slots[-1]), "art file=images/chassis.svg fit=stretch"]
    for i, sl in enumerate(slots):
        k, px = "s%02d_" % sl, PX0 + i * PPITCH
        for fam in range(5):                         # 0-3 the kits; 4 the 9W9 kick (denser)
            kit = FAMILIES[min(fam, 3)]
            f, geo, cells = FAM[kit], (DENSE if fam == 4 else REG), (CELLS_DENSE if fam == 4 else CELLS)
            w = "when=%sfam:%d" % (k, fam)
            out.append("art file=images/panel_%s.svg x=%d y=%d w=%d h=%d %s" % ("9w9_dense" if fam == 4 else kit, px, TOP, PW, BOT - TOP, w))
            # the voice menu doubles as the module's title: the voice's name, in the kit's colour
            out.append('popup cx=%d cy=%d w=250 cw=118 h=34 label="" key=%ssrc groups="%s" accent=%s field=none %s' % (
                px + 147, TOP + 19, k, GROUPS, f["title"], w))
            cx, cy = _cell(px, geo, cells, "dist")
            out.append('popup cx=%d cy=%d w=130 h=44 label="" key=%sdist accent=%s field=none %s' % (cx, cy + 22, k, f["dist"], w))
            for name, label in (("level", "LEVEL"), ("tune", "TUNE"), ("decay", "DECAY"), ("drive", "DRIVE"), ("pan", "PAN"),
                                ("rev", "REV"), ("dly", "DLY")):
                cx, cy = _cell(px, geo, cells, name)
                strip = "knob_8w8_level" if (kit == "8w8" and name == "level") else "knob_%s" % kit
                out.append('knob cx=%d cy=%d r=%d label="%s" key=%s%s strip=images/%s.png ink=%s ink_dim=%s %s' % (
                    cx, cy, geo["r"], label, k, name, strip, f["ink"], f["dim"], w))
        extra_lines(out, k, px)
    out.append('qlinks "S%d - S%d" = %s' % (slots[0], slots[-1], ",".join(
        "s%02d_%s" % (s, kk) for s in slots for kk in ("src", "level", "tune", "decay"))))
    for sl in slots:
        keys = ["src", "level", "tune", "decay", "drive", "dist", "pan", "rev", "dly"]
        out.append('qlinks "SLOT %d" = %s' % (sl, ",".join("s%02d_%s" % (sl, kk) for kk in keys[:8])))
        out.append('qlinks "SLOT %d CHARACTER" = %s' % (sl, ",".join("s%02d_%s" % (sl, kk) for kk in (
            "attack", "tone", "snappy", "noise", "rate", "sweep", "pmod", "ndecay"))))


def knob8(out, cx, cy, label, key, r=None):
    f = FAM["8w8"]
    out.append('knob cx=%d cy=%d r=%d label="%s" key=%s strip=images/knob_8w8.png ink=%s ink_dim=%s' % (cx, cy, r or REG["r"], label, key, f["ink"], f["dim"]))


def popup8(out, cx, cy, key):
    out.append('popup cx=%d cy=%d w=130 h=44 label="" key=%s accent=%s field=none' % (cx, cy + 22, key, FAM["8w8"]["dist"]))


def fx_page(out):
    """FX tab: REVERB, DELAY and MASTER modules, each with a key that switches the kit's own stage off (the sends then only
    leave through TR-MPC Tap FX); and a RANDOMISE tab: the sixteen slot keys over two modules, the amount and the two buttons."""
    out += ["", "[tab FX]", "art file=images/chassis_fx.svg fit=stretch"]
    mods = [("REVERB", "int_rev", "REVERB", [("knob", 0, 0, "DECAY", "fx_rev_decay"), ("knob", 1, 0, "TONE", "fx_rev_tone"),
                                         ("knob", 0, 1, "HPF", "fx_rev_hpf"), ("knob", 1, 1, "LEVEL", "fx_rev_level")]),
            ("DELAY", "int_dly", "DELAY", [("popup", 0, 0, "TIME", "fx_dly_time"), ("knob", 1, 0, "FEEDBACK", "fx_dly_fdbk"),
                                       ("knob", 0, 1, "TONE", "fx_dly_tone"), ("knob", 1, 1, "HPF", "fx_dly_hpf"),
                                       ("knob", 0, 2, "LEVEL", "fx_dly_level")]),
            ("MASTER", "int_comp", "COMP", [("popup", 0, 0, "MASTER DIST", "fx_master_dist"), ("knob", 1, 0, "DRIVE", "fx_master_drive"),
                                          ("knob", 0, 1, "COMP", "fx_comp"), ("knob", 1, 1, "VOLUME", "fx_volume")])]
    for i, (title, ikey, btn, ctrls) in enumerate(mods):
        px = PX0 + i * PPITCH
        pops = [(CELL_X[c], REG["row0"] + r * REG["pitch"] + 22, cap) for kind, c, r, cap, key in ctrls if kind == "popup"]
        svg = faceplate("8w8", pops, title=title, watermark=False, arrow=False, screws=("tr", "bl", "br"))
        svg = caption_on(svg, px, "LIT = ON   DARK = SEND ONLY", 520, 12)
        _write("images/panel_fx%d.svg" % (i + 1), svg)
        out.append("art file=images/panel_fx%d.svg x=%d y=%d w=%d h=%d" % (i + 1, px, TOP, PW, BOT - TOP))
        for kind, c, r, label, key in ctrls:
            cx, cy = px + CELL_X[c], REG["row0"] + r * REG["pitch"]
            popup8(out, cx, cy, key) if kind == "popup" else knob8(out, cx, cy, label, key)
        out.append('toggle cx=%d cy=%d label="" key=%s %s' % (px + PW // 2, 590, ikey, write_button("btn_" + ikey, 260, 84, btn, ORANGE, 34)))
    px = PX0 + 3 * PPITCH
    _write("images/panel_fx4.svg", blank_plate())
    out.append("art file=images/panel_fx4.svg x=%d y=%d w=%d h=%d" % (px, TOP, PW, BOT - TOP))
    out += ['qlinks "FX" = fx_rev_decay,fx_rev_tone,fx_rev_level,fx_dly_time,fx_dly_fdbk,fx_dly_level,fx_master_dist,fx_master_drive',
            'qlinks "REVERB" = fx_rev_decay,fx_rev_tone,fx_rev_hpf,fx_rev_level,int_rev',
            'qlinks "DELAY" = fx_dly_time,fx_dly_fdbk,fx_dly_tone,fx_dly_hpf,fx_dly_level,int_dly',
            'qlinks "MASTER" = fx_master_dist,fx_master_drive,fx_comp,fx_volume,int_comp']
    # RANDOMISE tab
    out += ["", "[tab RANDOMISE]", "art file=images/chassis_fx.svg fit=stretch"]
    for i, title in enumerate(("SELECT SLOTS 1-8", "SELECT SLOTS 9-16")):
        px = PX0 + i * PPITCH
        _write("images/panel_rnd%d.svg" % (i + 1), faceplate("8w8", title=title, watermark=False, arrow=False, screws=("tr", "bl", "br")))
        out.append("art file=images/panel_rnd%d.svg x=%d y=%d w=%d h=%d" % (i + 1, px, TOP, PW, BOT - TOP))
        for k in range(8):
            n = i * 8 + k
            out.append('toggle cx=%d cy=%d label="" key=rnd_s%02d %s' % (px + CELL_X[k % 2], 225 + (k // 2) * 125, n + 1,
                                                                           write_button("rslot%d" % (n + 1), 130, 100, str(n + 1), STEP_GREY, 52)))
    px = PX0 + 2 * PPITCH
    _write("images/panel_rnd3.svg", faceplate("8w8", title="SELECT", watermark=False, arrow=False, screws=("tr", "bl", "br")))
    out.append("art file=images/panel_rnd3.svg x=%d y=%d w=%d h=%d" % (px, TOP, PW, BOT - TOP))
    out.append('button cx=%d cy=%d label="" key=rnd_all %s' % (px + PW // 2, 260, write_button("btn_rnd_all", 260, 130, "SELECT ALL", STEP_GREY, 30)))
    out.append('button cx=%d cy=%d label="" key=rnd_none %s' % (px + PW // 2, 430, write_button("btn_rnd_none", 260, 130, "CLEAR", STEP_GREY, 38)))
    px = PX0 + 3 * PPITCH
    _write("images/panel_rnd4.svg", faceplate("8w8", title="RANDOMISE", watermark=False, arrow=False, screws=("tr", "bl", "br")))
    out.append("art file=images/panel_rnd4.svg x=%d y=%d w=%d h=%d" % (px, TOP, PW, BOT - TOP))
    knob8(out, px + PW // 2 - 3, 232, "AMOUNT", "rnd_amount", r=30)
    out.append('button cx=%d cy=%d label="" key=rnd_go %s' % (px + PW // 2, 420, write_button("btn_rnd_go", 260, 130, "PARAMETERS", ORANGE, 30)))
    out.append('button cx=%d cy=%d label="" key=rnd_go_voice %s' % (px + PW // 2, 590, write_button("btn_rnd_voice", 260, 130, "VOICES", ORANGE, 38)))
    out += ['qlinks "RANDOMISE" = rnd_amount,rnd_go,rnd_go_voice,rnd_all,rnd_none',   # the first page names the tab
            'qlinks "SELECT SLOTS 1-8" = rnd_s01,rnd_s02,rnd_s03,rnd_s04,rnd_s05,rnd_s06,rnd_s07,rnd_s08',
            'qlinks "SELECT SLOTS 9-16" = rnd_s09,rnd_s10,rnd_s11,rnd_s12,rnd_s13,rnd_s14,rnd_s15,rnd_s16']


def build(pages=(0, 1, 2, 3), fx=True, rnd=True):
    images = os.path.join(PORT, "images")
    vendor_knobs()
    _write("images/chassis.svg", chassis_svg("5ec2b7"))
    _write("images/chassis_fx.svg", chassis_svg(ORANGE))
    for kit in FAMILIES:
        cx, cy = CELL_X[0], REG["row0"] + 22 + TOP * 0
        _write("images/panel_%s.svg" % kit, faceplate(kit, [(CELL_X[0], REG["row0"] + 22, "DISTORTION")]))
    _write("images/panel_9w9_dense.svg", faceplate("9w9", [(CELL_X[0], DENSE["row0"] + 22, "DISTORTION")]))
    out = ["# TR-MPC skin (full): every slot a module that reskins itself to the drum port its voice comes from. Generated by tools/gen_trmpc_full.py.",
           THEME]
    for page in pages:
        voice_page(out, page)
    if fx:
        fx_page(out)
    return "\n".join(out) + "\n"


def main():
    os.makedirs(os.path.join(PORT, "layouts"), exist_ok=True)
    _write("layouts/full.conf", build())
    _write("layouts/full_preview.conf", build(pages=(1,), fx=False, rnd=False))
    _write("layouts/full_fx_preview.conf", build(pages=(), fx=True, rnd=False))
    _write("skin_full.css", CSS)
    print("wrote layouts/{full,full_preview,full_fx_preview}.conf, skin_full.css, images/")


if __name__ == "__main__":
    main()
