"""Skin for "TR-MPC Tap FX" in the TR-MPC look: the same chassis, 808 faceplates, screws and lettering as the TR-MPC skin
(everything comes from gen_trmpc_full). Writes ports/trkit/tapfx/{layout.conf,skin_tap.css,images/}.
Run:  bash tools/gen_skins_docker.sh gen_trmpc_tap.py"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_drum_skins as drum            # noqa: E402,F401
import gen_trmpc_full as full            # noqa: E402

OUT = os.path.join(full.ROOT, "ports", "trkit", "tapfx")


def write(path, text):
    p = os.path.join(OUT, path)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w", newline="\n").write(text)


def chassis():
    """full.chassis_svg with its own tagline (the lettering is outlined, so it is drawn again rather than replaced)."""
    hy = drum.HEADER_CY - full.Y_OFF
    logo, _ = drum.text_path("Eurostile", "TR-MPC TAP FX", 24, hy, 30, full.ORANGE)
    tag, _ = drum.text_path("Helvetica", "SLOTS AND SENDS OUT TO THEIR OWN MPC TRACKS", 24 + 13 * 15 * 6 // 2 + 120, hy + 4, 13, "c9c4b3", spacing=2, bold=0.02)
    d = [drum.DEFS, drum.base("8w8"), logo, tag,
         '<rect x="0" y="%d" width="%d" height="2" fill="#%s" fill-opacity="0.7"/>' % (drum.HEAD_Y1 - full.Y_OFF - 3, full.W, full.ORANGE)]
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d">%s</svg>\n' % (full.W, full.H, full.W, full.H, "".join(d))


def build():
    import shutil
    os.makedirs(os.path.join(OUT, "images"), exist_ok=True)
    shutil.copy(os.path.join(full.PORT, "images", "knob_8w8.png"), os.path.join(OUT, "images", "knob_8w8.png"))
    write("images/chassis.svg", chassis())
    titles = ["SLOTS 1-8", "SLOTS 9-16", "SENDS", "INPUT"]
    for i, t in enumerate(titles):
        write("images/panel_%d.svg" % (i + 1), full.faceplate("8w8", title=t, watermark=False, arrow=False, screws=("tr", "bl", "br")))
    out = ["# TR-MPC Tap FX skin. Generated by tools/gen_trmpc_tap.py.",
           full.THEME.replace("art_css=skin_full.css", "art_css=skin_tap.css"),
           "", "[tab TAP FX]", "art file=images/chassis.svg fit=stretch"]
    BW, BH, ROWS = 130, 100, (225, 350, 475, 600)
    for i in range(4):
        px = full.PX0 + i * full.PPITCH
        out.append("art file=images/panel_%d.svg x=%d y=%d w=%d h=%d" % (i + 1, px, full.TOP, full.PW, full.BOT - full.TOP))
        if i < 2:
            for k in range(8):                     # two columns of four; the key colour steps down a row at a time
                n = i * 8 + k
                col, row = k % 2, k // 2
                for lit in (0, 1):
                    write("images/slot%d_%s.svg" % (n + 1, "on" if lit else "off"), full.button_svg(BW, BH, str(n + 1), full.STEP_GREY, lit, 52))
                out.append('toggle cx=%d cy=%d label="" key=src%d img=images/slot%d_off.svg img_on=images/slot%d_on.svg w=%d h=%d'
                           % (px + full.CELL_X[col], ROWS[row], n + 1, n + 1, n + 1, BW, BH))
    px = full.PX0 + 2 * full.PPITCH
    for name, key, row in (("REVERB", "src_rev", 0), ("DELAY", "src_del", 1)):
        for lit in (0, 1):
            write("images/%s_%s.svg" % (key, "on" if lit else "off"), full.button_svg(260, 220, name, full.ORANGE, lit, 52))
        out.append('toggle cx=%d cy=%d label="" key=%s img=images/%s_off.svg img_on=images/%s_on.svg w=260 h=220' % (px + full.PW // 2, 305 + row * 255, key, key, key))
    px = full.PX0 + 3 * full.PPITCH
    for lit in (0, 1):
        write("images/through_%s.svg" % ("on" if lit else "off"), full.button_svg(260, 220, "THRU", "5ec2b7", lit, 52))
    out.append('toggle cx=%d cy=305 label="" key=through img=images/through_off.svg img_on=images/through_on.svg w=260 h=220' % (px + full.PW // 2))
    out.append('qlinks "SLOTS 1-8" = src1,src2,src3,src4,src5,src6,src7,src8')
    out.append('qlinks "SLOTS 9-16" = src9,src10,src11,src12,src13,src14,src15,src16')
    out.append('qlinks "SENDS" = src_rev,src_del,through')
    write("layout.conf", "\n".join(out) + "\n")
    write("skin_tap.css", full.CSS.replace("gen_trmpc_full.py", "gen_trmpc_tap.py"))


if __name__ == "__main__":
    build()
    print("wrote ports/trkit/tapfx/{layout.conf,skin_tap.css,images/}")
