/* Generated by scripts/gen_params.py — DO NOT EDIT BY HAND.
 *
 * module.json is capped at 8 KB by Schwung's loader, so chain_params and the
 * page hierarchy are served dynamically from the DSP via get_param().
 *
 * The pot and enum tables below define storage order for the state blob.
 * Appending is safe; reordering breaks every saved patch.
 */
#ifndef SC808_PARAMS_H
#define SC808_PARAMS_H

typedef enum { SC808_LIN = 0, SC808_EXP = 1 } sc808_curve_t;

typedef struct {
    const char    *key;
    float          min;
    float          max;
    sc808_curve_t  curve;
    int            def;      /* default POT position, 0..127 */
} sc808_pot_t;

typedef struct {
    const char *key;
    int         count;      /* number of options */
    int         def;
} sc808_enum_t;

#define SC808_NUM_POTS  110
#define SC808_NUM_ENUMS 20

static const sc808_pot_t g_sc808_pots[SC808_NUM_POTS] = {
    { "bd_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "bd_attack",     0.0000f,     1.0000f, SC808_LIN,  24 },
    { "bd_decay",     0.1000f,     8.0000f, SC808_EXP,  87 },
    { "bd_tone",     0.0000f,     6.0000f, SC808_LIN,  42 },
    { "bd_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "bd_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "sd_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "sd_decay",     0.1000f,     8.0000f, SC808_EXP, 108 },
    { "sd_snappy",     0.0000f,     1.0000f, SC808_LIN,  89 },
    { "sd_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "sd_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "lt_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "lt_decay",     0.0600f,     2.0000f, SC808_EXP,  68 },
    { "lt_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "lt_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "mt_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "mt_decay",     0.0600f,     2.0000f, SC808_EXP,  56 },
    { "mt_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "mt_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ht_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "ht_decay",     0.0600f,     2.0000f, SC808_EXP,  53 },
    { "ht_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ht_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "lc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "lc_decay",     0.0600f,     2.0000f, SC808_EXP,  58 },
    { "lc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "lc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "mc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "mc_decay",     0.0600f,     2.0000f, SC808_EXP,  36 },
    { "mc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "mc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "hc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "hc_decay",     0.0600f,     2.0000f, SC808_EXP,  34 },
    { "hc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "hc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "rs_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "rs_decay",     0.0050f,     0.2000f, SC808_EXP,  40 },
    { "rs_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "rs_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cl_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "cl_decay",     0.0000f,     1.0000f, SC808_LIN,  64 },
    { "cl_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cl_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ma_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "ma_attack",     0.0000f,     1.0000f, SC808_LIN,  32 },
    { "ma_decay",     0.0100f,     0.3000f, SC808_EXP,  51 },
    { "ma_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ma_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cp_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "cp_decay",     0.3500f,     2.8000f, SC808_EXP,  64 },
    { "cp_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cp_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cb_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "cb_decay",     0.1000f,     2.0000f, SC808_EXP,  62 },
    { "cb_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cb_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ch_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "ch_decay",     0.0300f,     0.5000f, SC808_EXP,  47 },
    { "ch_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ch_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "oh_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "oh_decay",     0.0800f,     1.5000f, SC808_EXP,  74 },
    { "oh_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "oh_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cy_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "cy_decay",     0.4000f,     6.0000f, SC808_EXP,  70 },
    { "cy_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cy_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "master_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "comp",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "volume",     0.0000f,     1.0000f, SC808_LIN, 100 },
    { "vel_depth",     0.0000f,     1.0000f, SC808_LIN, 127 },
    { "sd_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "sd_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "lt_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "lt_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "mt_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "mt_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ht_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ht_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "lc_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "lc_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "mc_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "mc_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "hc_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "hc_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "rs_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "rs_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cl_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cl_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ma_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ma_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cp_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cp_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cb_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cb_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ch_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "ch_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "oh_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "oh_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cy_rev",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "cy_dly",     0.0000f,     1.0000f, SC808_LIN,   0 },
    { "rev_decay",     0.2000f,     0.9300f, SC808_LIN,  73 },
    { "rev_tone",     0.0000f,     1.0000f, SC808_LIN,  57 },
    { "rev_hpf",    30.0000f,   800.0000f, SC808_EXP,  62 },
    { "rev_level",     0.0000f,     1.2000f, SC808_LIN,  85 },
    { "dly_fdbk",     0.0000f,     0.8500f, SC808_LIN,  52 },
    { "dly_tone",     0.0000f,     1.0000f, SC808_LIN,  51 },
    { "dly_hpf",    30.0000f,   800.0000f, SC808_EXP,  62 },
    { "dly_level",     0.0000f,     1.2000f, SC808_LIN,  85 },
};

static const sc808_enum_t g_sc808_enums[SC808_NUM_ENUMS] = {
    { "bd_dist_type",  7,  0 },
    { "sd_dist_type",  7,  0 },
    { "lt_dist_type",  7,  0 },
    { "mt_dist_type",  7,  0 },
    { "ht_dist_type",  7,  0 },
    { "lc_dist_type",  7,  0 },
    { "mc_dist_type",  7,  0 },
    { "hc_dist_type",  7,  0 },
    { "rs_dist_type",  7,  0 },
    { "cl_dist_type",  7,  0 },
    { "ma_dist_type",  7,  0 },
    { "cp_dist_type",  7,  0 },
    { "cb_dist_type",  7,  0 },
    { "ch_dist_type",  7,  0 },
    { "hh_choke",  3,  1 },
    { "oh_dist_type",  7,  0 },
    { "cy_dist_type",  7,  0 },
    { "master_dist",  8,  0 },
    { "note_map",  2,  0 },
    { "dly_time", 13,  7 },
};

#define SC808_CHAIN_PARAMS_LEN 11949
static const char sc808_chain_params_json[] =
    "[{\"key\":\"bd_tune\",\"name\":\"BD Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"bd_attack\",\""
    "name\":\"BD Attack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":24,\"viz\":false},{\"key\":\"bd_decay\",\"name\":"
    "\"BD Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":87},{\"key\":\"bd_tone\",\"name\":\"BD Tone\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"default\":42},{\"key\":\"bd_drive\",\"name\":\"BD Drive\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"default\":0},{\"key\":\"bd_dist_type\",\"name\":\"BD Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\","
    "\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"bd_level\",\"name\":\"BD Level\",\"type\":\"int\",\"m"
    "in\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"sd_tune\",\"name\":\"SD Tune\",\"type\":\"int\","
    "\"min\":0,\"max\":127,\"default\":64},{\"key\":\"sd_decay\",\"name\":\"SD Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":108},{\"key\":\"sd_snappy\",\"name\":\"SD Snappy\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":89},{\"k"
    "ey\":\"sd_drive\",\"name\":\"SD Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"sd_dist_type\",\""
    "name\":\"SD Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"d"
    "efault\":0},{\"key\":\"sd_level\",\"name\":\"SD Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"k"
    "ind\":\"fader\"}},{\"key\":\"lt_tune\",\"name\":\"LT Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\""
    ":\"lt_decay\",\"name\":\"LT Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":68},{\"key\":\"lt_drive\",\"name\":"
    "\"LT Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lt_dist_type\",\"name\":\"LT Distortion\","
    "\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"lt_"
    "level\",\"name\":\"LT Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":"
    "\"mt_tune\",\"name\":\"MT Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"mt_decay\",\"name\":\"MT"
    " Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":56},{\"key\":\"mt_drive\",\"name\":\"MT Drive\",\"type\":\"int"
    "\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"mt_dist_type\",\"name\":\"MT Distortion\",\"type\":\"enum\",\"options"
    "\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"mt_level\",\"name\":\"MT Leve"
    "l\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ht_tune\",\"name\":\"HT T"
    "une\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ht_decay\",\"name\":\"HT Decay\",\"type\":\"int\",\""
    "min\":0,\"max\":127,\"default\":53},{\"key\":\"ht_drive\",\"name\":\"HT Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":0},{\"key\":\"ht_dist_type\",\"name\":\"HT Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT"
    "\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ht_level\",\"name\":\"HT Level\",\"type\":\"int\",\"min\":"
    "0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lc_tune\",\"name\":\"LC Tune\",\"type\":\"int\",\"min"
    "\":0,\"max\":127,\"default\":64},{\"key\":\"lc_decay\",\"name\":\"LC Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":58},{\"key\":\"lc_drive\",\"name\":\"LC Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lc_"
    "dist_type\",\"name\":\"LC Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\""
    ",\"Crush\"],\"default\":0},{\"key\":\"lc_level\",\"name\":\"LC Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":"
    "64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"mc_tune\",\"name\":\"MC Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default"
    "\":64},{\"key\":\"mc_decay\",\"name\":\"MC Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":36},{\"key\":\"mc_dr"
    "ive\",\"name\":\"MC Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"mc_dist_type\",\"name\":\"MC "
    "Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0}"
    ",{\"key\":\"mc_level\",\"name\":\"MC Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fade"
    "r\"}},{\"key\":\"hc_tune\",\"name\":\"HC Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"hc_decay"
    "\",\"name\":\"HC Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":34},{\"key\":\"hc_drive\",\"name\":\"HC Drive\""
    ",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hc_dist_type\",\"name\":\"HC Distortion\",\"type\":\"en"
    "um\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"hc_level\",\"na"
    "me\":\"HC Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"rs_tune\","
    "\"name\":\"RS Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"rs_decay\",\"name\":\"RS Decay\",\"t"
    "ype\":\"int\",\"min\":0,\"max\":127,\"default\":40},{\"key\":\"rs_drive\",\"name\":\"RS Drive\",\"type\":\"int\",\"min\":0,"
    "\"max\":127,\"default\":0},{\"key\":\"rs_dist_type\",\"name\":\"RS Distortion\",\"type\":\"enum\",\"options\":[\"Diode\""
    ",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"rs_level\",\"name\":\"RS Level\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cl_tune\",\"name\":\"CL Tune\",\"type"
    "\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cl_decay\",\"name\":\"CL Decay\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":64},{\"key\":\"cl_drive\",\"name\":\"CL Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0}"
    ",{\"key\":\"cl_dist_type\",\"name\":\"CL Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"P"
    "DIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cl_level\",\"name\":\"CL Level\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ma_tune\",\"name\":\"MA Tune\",\"type\":\"int\",\"min\":0,\"max\":"
    "127,\"default\":64},{\"key\":\"ma_attack\",\"name\":\"MA Attack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":32}"
    ",{\"key\":\"ma_decay\",\"name\":\"MA Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":51},{\"key\":\"ma_drive\","
    "\"name\":\"MA Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ma_dist_type\",\"name\":\"MA Disto"
    "rtion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"ke"
    "y\":\"ma_level\",\"name\":\"MA Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},"
    "{\"key\":\"cp_tune\",\"name\":\"CP Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cp_decay\",\"na"
    "me\":\"CP Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cp_drive\",\"name\":\"CP Drive\",\"typ"
    "e\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cp_dist_type\",\"name\":\"CP Distortion\",\"type\":\"enum\",\""
    "options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cp_level\",\"name\":\""
    "CP Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cb_tune\",\"name"
    "\":\"CB Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cb_decay\",\"name\":\"CB Decay\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"default\":62},{\"key\":\"cb_drive\",\"name\":\"CB Drive\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":0},{\"key\":\"cb_dist_type\",\"name\":\"CB Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Cli"
    "p\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cb_level\",\"name\":\"CB Level\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ch_tune\",\"name\":\"CH Tune\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ch_decay\",\"name\":\"CH Decay\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"default\":47},{\"key\":\"ch_drive\",\"name\":\"CH Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"ke"
    "y\":\"ch_dist_type\",\"name\":\"CH Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\""
    ",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ch_level\",\"name\":\"CH Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"hh_choke\",\"name\":\"Choke\",\"type\":\"enum\",\"options\":[\"Off\",\"C"
    "H>OH\",\"Mutual\"],\"default\":1},{\"key\":\"oh_tune\",\"name\":\"OH Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"defau"
    "lt\":64},{\"key\":\"oh_decay\",\"name\":\"OH Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":74},{\"key\":\"oh_"
    "drive\",\"name\":\"OH Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"oh_dist_type\",\"name\":\"O"
    "H Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":"
    "0},{\"key\":\"oh_level\",\"name\":\"OH Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fa"
    "der\"}},{\"key\":\"cy_tune\",\"name\":\"CY Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cy_dec"
    "ay\",\"name\":\"CY Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":70},{\"key\":\"cy_drive\",\"name\":\"CY Driv"
    "e\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_dist_type\",\"name\":\"CY Distortion\",\"type\":\""
    "enum\",\"options\":[\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cy_level\",\""
    "name\":\"CY Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"master_"
    "dist\",\"name\":\"Master Dist\",\"type\":\"enum\",\"options\":[\"Off\",\"Diode\",\"Clip\",\"SAT\",\"BFZ\",\"PDIST\",\"Fold\","
    "\"Crush\"],\"default\":0},{\"key\":\"master_drive\",\"name\":\"Master Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":0},{\"key\":\"comp\",\"name\":\"Comp\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"volume\",\"n"
    "ame\":\"Volume\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":100,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"vel_depth"
    "\",\"name\":\"Velocity\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"note_map\",\"name\":\"Note Map"
    "\",\"type\":\"enum\",\"options\":[\"Rack 36\",\"GM\"],\"default\":0},{\"key\":\"sd_rev\",\"name\":\"SD Rev\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"sd_dly\",\"name\":\"SD Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":0},{\"key\":\"lt_rev\",\"name\":\"LT Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lt_dly\","
    "\"name\":\"LT Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"mt_rev\",\"name\":\"MT Rev\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"mt_dly\",\"name\":\"MT Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":0},{\"key\":\"ht_rev\",\"name\":\"HT Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ht_d"
    "ly\",\"name\":\"HT Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lc_rev\",\"name\":\"LC Rev\",\"typ"
    "e\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lc_dly\",\"name\":\"LC Dly\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"default\":0},{\"key\":\"mc_rev\",\"name\":\"MC Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\""
    "mc_dly\",\"name\":\"MC Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hc_rev\",\"name\":\"HC Rev\","
    "\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hc_dly\",\"name\":\"HC Dly\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":0},{\"key\":\"rs_rev\",\"name\":\"RS Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"ke"
    "y\":\"rs_dly\",\"name\":\"RS Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_rev\",\"name\":\"CL R"
    "ev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_dly\",\"name\":\"CL Dly\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":0},{\"key\":\"ma_rev\",\"name\":\"MA Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},"
    "{\"key\":\"ma_dly\",\"name\":\"MA Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cp_rev\",\"name\":\""
    "CP Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cp_dly\",\"name\":\"CP Dly\",\"type\":\"int\",\"mi"
    "n\":0,\"max\":127,\"default\":0},{\"key\":\"cb_rev\",\"name\":\"CB Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\""
    ":0},{\"key\":\"cb_dly\",\"name\":\"CB Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ch_rev\",\"nam"
    "e\":\"CH Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ch_dly\",\"name\":\"CH Dly\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"oh_rev\",\"name\":\"OH Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":0},{\"key\":\"oh_dly\",\"name\":\"OH Dly\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_rev\","
    "\"name\":\"CY Rev\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cy_dly\",\"name\":\"CY Dly\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"rev_decay\",\"name\":\"REV Decay\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":73},{\"key\":\"rev_tone\",\"name\":\"REV Tone\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":57},"
    "{\"key\":\"rev_hpf\",\"name\":\"REV HPF\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":62},{\"key\":\"rev_level\",\"n"
    "ame\":\"REV Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":85,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"dly_tim"
    "e\",\"name\":\"DLY Time\",\"type\":\"enum\",\"options\":[\"1/32\",\"1/16T\",\"1/16\",\"1/8T\",\"1/16.\",\"1/8\",\"1/4T\",\"1/8"
    ".\",\"1/4\",\"1/2T\",\"1/4.\",\"1/2\",\"1/2.\"],\"default\":7},{\"key\":\"dly_fdbk\",\"name\":\"DLY Fdbk\",\"type\":\"int\",\""
    "min\":0,\"max\":127,\"default\":52},{\"key\":\"dly_tone\",\"name\":\"DLY Tone\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":51},{\"key\":\"dly_hpf\",\"name\":\"DLY HPF\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":62},{\"key\":\"d"
    "ly_level\",\"name\":\"DLY Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":85,\"viz\":{\"kind\":\"fader\"}},{\"k"
    "ey\":\"ui_focus\",\"name\":\"Focus\",\"type\":\"int\",\"min\":0,\"max\":16,\"default\":0},{\"key\":\"mutes\",\"name\":\"Mute"
    "s\",\"type\":\"int\",\"min\":0,\"max\":65535,\"default\":0}]";

#define SC808_UI_PAGES_LEN 7924
static const char sc808_ui_pages_json[] =
    "{\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\",\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd"
    "_tune\",\"bd_attack\",\"bd_decay\",\"bd_tone\",\"bd_drive\",\"bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd_t"
    "une\",\"label\":\"Tune\"},{\"key\":\"bd_attack\",\"label\":\"Attack\"},{\"key\":\"bd_decay\",\"label\":\"Decay\"},{\"key\":"
    "\"bd_tone\",\"label\":\"Tone\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":\"bd_dist_type\",\"label\":\"Distorti"
    "on\"},{\"key\":\"bd_level\",\"label\":\"Level\"}],\"note\":36,\"role\":\"kick\"},\"sd\":{\"name\":\"Snare\",\"knobs\":[\"sd_"
    "tune\",\"sd_decay\",\"sd_snappy\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"sd_rev\",\"sd_dly\"],\"params\":[{\"key"
    "\":\"sd_tune\",\"label\":\"Tune\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key\":\"sd_snappy\",\"label\":\"Snappy\"},"
    "{\"key\":\"sd_drive\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"sd_level\",\"la"
    "bel\":\"Level\"},{\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\":\"Dly\"}],\"note\":37,\"role\":\"snare"
    "\"},\"lt\":{\"name\":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\",\"lt_rev"
    "\",\"lt_dly\"],\"params\":[{\"key\":\"lt_tune\",\"label\":\"Tune\"},{\"key\":\"lt_decay\",\"label\":\"Decay\"},{\"key\":\"lt"
    "_drive\",\"label\":\"Drive\"},{\"key\":\"lt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lt_level\",\"label\":\"Leve"
    "l\"},{\"key\":\"lt_rev\",\"label\":\"Rev\"},{\"key\":\"lt_dly\",\"label\":\"Dly\"}],\"note\":38,\"role\":\"tom\"},\"mt\":{\"na"
    "me\":\"Mid Tom\",\"knobs\":[\"mt_tune\",\"mt_decay\",\"mt_drive\",\"mt_dist_type\",\"mt_level\",\"mt_rev\",\"mt_dly\"],"
    "\"params\":[{\"key\":\"mt_tune\",\"label\":\"Tune\"},{\"key\":\"mt_decay\",\"label\":\"Decay\"},{\"key\":\"mt_drive\",\"lab"
    "el\":\"Drive\"},{\"key\":\"mt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"mt_level\",\"label\":\"Level\"},{\"key\":\""
    "mt_rev\",\"label\":\"Rev\"},{\"key\":\"mt_dly\",\"label\":\"Dly\"}],\"note\":39,\"role\":\"tom\"},\"ht\":{\"name\":\"Hi Tom\""
    ",\"knobs\":[\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht_dist_type\",\"ht_level\",\"ht_rev\",\"ht_dly\"],\"params\":[{\"k"
    "ey\":\"ht_tune\",\"label\":\"Tune\"},{\"key\":\"ht_decay\",\"label\":\"Decay\"},{\"key\":\"ht_drive\",\"label\":\"Drive\"},"
    "{\"key\":\"ht_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ht_level\",\"label\":\"Level\"},{\"key\":\"ht_rev\",\"labe"
    "l\":\"Rev\"},{\"key\":\"ht_dly\",\"label\":\"Dly\"}],\"note\":40,\"role\":\"tom\"},\"lc\":{\"name\":\"Low Conga\",\"knobs\":["
    "\"lc_tune\",\"lc_decay\",\"lc_drive\",\"lc_dist_type\",\"lc_level\",\"lc_rev\",\"lc_dly\"],\"params\":[{\"key\":\"lc_tu"
    "ne\",\"label\":\"Tune\"},{\"key\":\"lc_decay\",\"label\":\"Decay\"},{\"key\":\"lc_drive\",\"label\":\"Drive\"},{\"key\":\"lc"
    "_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lc_level\",\"label\":\"Level\"},{\"key\":\"lc_rev\",\"label\":\"Rev\"},"
    "{\"key\":\"lc_dly\",\"label\":\"Dly\"}],\"note\":41,\"role\":\"conga\"},\"mc\":{\"name\":\"Mid Conga\",\"knobs\":[\"mc_tune"
    "\",\"mc_decay\",\"mc_drive\",\"mc_dist_type\",\"mc_level\",\"mc_rev\",\"mc_dly\"],\"params\":[{\"key\":\"mc_tune\",\"lab"
    "el\":\"Tune\"},{\"key\":\"mc_decay\",\"label\":\"Decay\"},{\"key\":\"mc_drive\",\"label\":\"Drive\"},{\"key\":\"mc_dist_ty"
    "pe\",\"label\":\"Distortion\"},{\"key\":\"mc_level\",\"label\":\"Level\"},{\"key\":\"mc_rev\",\"label\":\"Rev\"},{\"key\":\""
    "mc_dly\",\"label\":\"Dly\"}],\"note\":42,\"role\":\"conga\"},\"hc\":{\"name\":\"Hi Conga\",\"knobs\":[\"hc_tune\",\"hc_dec"
    "ay\",\"hc_drive\",\"hc_dist_type\",\"hc_level\",\"hc_rev\",\"hc_dly\"],\"params\":[{\"key\":\"hc_tune\",\"label\":\"Tune"
    "\"},{\"key\":\"hc_decay\",\"label\":\"Decay\"},{\"key\":\"hc_drive\",\"label\":\"Drive\"},{\"key\":\"hc_dist_type\",\"labe"
    "l\":\"Distortion\"},{\"key\":\"hc_level\",\"label\":\"Level\"},{\"key\":\"hc_rev\",\"label\":\"Rev\"},{\"key\":\"hc_dly\",\""
    "label\":\"Dly\"}],\"note\":43,\"role\":\"conga\"},\"rs\":{\"name\":\"Rim Shot\",\"knobs\":[\"rs_tune\",\"rs_decay\",\"rs_d"
    "rive\",\"rs_dist_type\",\"rs_level\",\"rs_rev\",\"rs_dly\"],\"params\":[{\"key\":\"rs_tune\",\"label\":\"Tune\"},{\"key\""
    ":\"rs_decay\",\"label\":\"Decay\"},{\"key\":\"rs_drive\",\"label\":\"Drive\"},{\"key\":\"rs_dist_type\",\"label\":\"Disto"
    "rtion\"},{\"key\":\"rs_level\",\"label\":\"Level\"},{\"key\":\"rs_rev\",\"label\":\"Rev\"},{\"key\":\"rs_dly\",\"label\":\"D"
    "ly\"}],\"note\":44,\"role\":\"rim\"},\"cl\":{\"name\":\"Claves\",\"knobs\":[\"cl_tune\",\"cl_decay\",\"cl_drive\",\"cl_dis"
    "t_type\",\"cl_level\",\"cl_rev\",\"cl_dly\"],\"params\":[{\"key\":\"cl_tune\",\"label\":\"Tune\"},{\"key\":\"cl_decay\",\""
    "label\":\"Decay\"},{\"key\":\"cl_drive\",\"label\":\"Drive\"},{\"key\":\"cl_dist_type\",\"label\":\"Distortion\"},{\"key"
    "\":\"cl_level\",\"label\":\"Level\"},{\"key\":\"cl_rev\",\"label\":\"Rev\"},{\"key\":\"cl_dly\",\"label\":\"Dly\"}],\"note\":"
    "45,\"role\":\"clave\"},\"ma\":{\"name\":\"Maracas\",\"knobs\":[\"ma_tune\",\"ma_attack\",\"ma_decay\",\"ma_drive\",\"ma_d"
    "ist_type\",\"ma_level\",\"ma_rev\",\"ma_dly\"],\"params\":[{\"key\":\"ma_tune\",\"label\":\"Tune\"},{\"key\":\"ma_attack"
    "\",\"label\":\"Attack\"},{\"key\":\"ma_decay\",\"label\":\"Decay\"},{\"key\":\"ma_drive\",\"label\":\"Drive\"},{\"key\":\"ma"
    "_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ma_level\",\"label\":\"Level\"},{\"key\":\"ma_rev\",\"label\":\"Rev\"},"
    "{\"key\":\"ma_dly\",\"label\":\"Dly\"}],\"note\":46,\"role\":\"shaker\"},\"cp\":{\"name\":\"Hand Clap\",\"knobs\":[\"cp_tun"
    "e\",\"cp_decay\",\"cp_drive\",\"cp_dist_type\",\"cp_level\",\"cp_rev\",\"cp_dly\"],\"params\":[{\"key\":\"cp_tune\",\"la"
    "bel\":\"Tune\"},{\"key\":\"cp_decay\",\"label\":\"Decay\"},{\"key\":\"cp_drive\",\"label\":\"Drive\"},{\"key\":\"cp_dist_t"
    "ype\",\"label\":\"Distortion\"},{\"key\":\"cp_level\",\"label\":\"Level\"},{\"key\":\"cp_rev\",\"label\":\"Rev\"},{\"key\":"
    "\"cp_dly\",\"label\":\"Dly\"}],\"note\":47,\"role\":\"clap\"},\"cb\":{\"name\":\"Cowbell\",\"knobs\":[\"cb_tune\",\"cb_deca"
    "y\",\"cb_drive\",\"cb_dist_type\",\"cb_level\",\"cb_rev\",\"cb_dly\"],\"params\":[{\"key\":\"cb_tune\",\"label\":\"Tune\""
    "},{\"key\":\"cb_decay\",\"label\":\"Decay\"},{\"key\":\"cb_drive\",\"label\":\"Drive\"},{\"key\":\"cb_dist_type\",\"label"
    "\":\"Distortion\"},{\"key\":\"cb_level\",\"label\":\"Level\"},{\"key\":\"cb_rev\",\"label\":\"Rev\"},{\"key\":\"cb_dly\",\"l"
    "abel\":\"Dly\"}],\"note\":48,\"role\":\"cowbell\"},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"ch_tune\",\"ch_decay\",\"c"
    "h_drive\",\"ch_dist_type\",\"ch_level\",\"hh_choke\",\"ch_rev\",\"ch_dly\"],\"params\":[{\"key\":\"ch_tune\",\"label\":"
    "\"Tune\"},{\"key\":\"ch_decay\",\"label\":\"Decay\"},{\"key\":\"ch_drive\",\"label\":\"Drive\"},{\"key\":\"ch_dist_type\","
    "\"label\":\"Distortion\"},{\"key\":\"ch_level\",\"label\":\"Level\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\""
    "ch_rev\",\"label\":\"Rev\"},{\"key\":\"ch_dly\",\"label\":\"Dly\"}],\"note\":49,\"role\":\"hat\"},\"oh\":{\"name\":\"Open Ha"
    "t\",\"knobs\":[\"oh_tune\",\"oh_decay\",\"oh_drive\",\"oh_dist_type\",\"oh_level\",\"oh_rev\",\"oh_dly\"],\"params\":[{"
    "\"key\":\"oh_tune\",\"label\":\"Tune\"},{\"key\":\"oh_decay\",\"label\":\"Decay\"},{\"key\":\"oh_drive\",\"label\":\"Drive\""
    "},{\"key\":\"oh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"oh_level\",\"label\":\"Level\"},{\"key\":\"oh_rev\",\"la"
    "bel\":\"Rev\"},{\"key\":\"oh_dly\",\"label\":\"Dly\"}],\"note\":50,\"role\":\"hat\"},\"cy\":{\"name\":\"Cymbal\",\"knobs\":[\""
    "cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\",\"cy_rev\",\"cy_dly\"],\"params\":[{\"key\":\"cy_tun"
    "e\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\"key\":\"cy_drive\",\"label\":\"Drive\"},{\"key\":\"cy_"
    "dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"label\":\"Level\"},{\"key\":\"cy_rev\",\"label\":\"Rev\"},{"
    "\"key\":\"cy_dly\",\"label\":\"Dly\"}],\"note\":51,\"role\":\"cymbal\"},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_decay"
    "\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_tone\","
    "\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"},{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"name\":"
    "\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_tone\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_time\""
    ",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdbk\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly_hpf"
    "\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Level\"}]},\"root\":{\"name\":\"8W8\",\"knobs\":[\"master_dist\",\""
    "master_drive\",\"comp\",\"volume\",\"vel_depth\"],\"params\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd"
    "\",\"label\":\"Snare\"},{\"level\":\"lt\",\"label\":\"Low Tom\"},{\"level\":\"mt\",\"label\":\"Mid Tom\"},{\"level\":\"ht\",\""
    "label\":\"Hi Tom\"},{\"level\":\"lc\",\"label\":\"Low Conga\"},{\"level\":\"mc\",\"label\":\"Mid Conga\"},{\"level\":\"hc\""
    ",\"label\":\"Hi Conga\"},{\"level\":\"rs\",\"label\":\"Rim Shot\"},{\"level\":\"cl\",\"label\":\"Claves\"},{\"level\":\"ma\""
    ",\"label\":\"Maracas\"},{\"level\":\"cp\",\"label\":\"Hand Clap\"},{\"level\":\"cb\",\"label\":\"Cowbell\"},{\"level\":\"ch"
    "\",\"label\":\"Closed Hat\"},{\"level\":\"oh\",\"label\":\"Open Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\""
    "rev\",\"label\":\"Reverb\"},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{"
    "\"key\":\"master_drive\",\"label\":\"Master Drive\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"volume\",\"label\":\""
    "Volume\"},{\"key\":\"vel_depth\",\"label\":\"Velocity\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\"note_map\""
    ",\"label\":\"Note Map\"}]}}}";

/* The same hierarchy carrying the General MIDI note map, for note_map == 1.
 * The map is switchable at runtime, so one static answer would be wrong half
 * the time; get_param picks. */
#define SC808_UI_PAGES_GM_LEN 7924
static const char sc808_ui_pages_gm_json[] =
    "{\"pad_layout\":\"drums\",\"focus_param\":\"ui_focus_level\",\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd"
    "_tune\",\"bd_attack\",\"bd_decay\",\"bd_tone\",\"bd_drive\",\"bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd_t"
    "une\",\"label\":\"Tune\"},{\"key\":\"bd_attack\",\"label\":\"Attack\"},{\"key\":\"bd_decay\",\"label\":\"Decay\"},{\"key\":"
    "\"bd_tone\",\"label\":\"Tone\"},{\"key\":\"bd_drive\",\"label\":\"Drive\"},{\"key\":\"bd_dist_type\",\"label\":\"Distorti"
    "on\"},{\"key\":\"bd_level\",\"label\":\"Level\"}],\"note\":36,\"role\":\"kick\"},\"sd\":{\"name\":\"Snare\",\"knobs\":[\"sd_"
    "tune\",\"sd_decay\",\"sd_snappy\",\"sd_drive\",\"sd_dist_type\",\"sd_level\",\"sd_rev\",\"sd_dly\"],\"params\":[{\"key"
    "\":\"sd_tune\",\"label\":\"Tune\"},{\"key\":\"sd_decay\",\"label\":\"Decay\"},{\"key\":\"sd_snappy\",\"label\":\"Snappy\"},"
    "{\"key\":\"sd_drive\",\"label\":\"Drive\"},{\"key\":\"sd_dist_type\",\"label\":\"Distortion\"},{\"key\":\"sd_level\",\"la"
    "bel\":\"Level\"},{\"key\":\"sd_rev\",\"label\":\"Rev\"},{\"key\":\"sd_dly\",\"label\":\"Dly\"}],\"note\":38,\"role\":\"snare"
    "\"},\"lt\":{\"name\":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\",\"lt_rev"
    "\",\"lt_dly\"],\"params\":[{\"key\":\"lt_tune\",\"label\":\"Tune\"},{\"key\":\"lt_decay\",\"label\":\"Decay\"},{\"key\":\"lt"
    "_drive\",\"label\":\"Drive\"},{\"key\":\"lt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lt_level\",\"label\":\"Leve"
    "l\"},{\"key\":\"lt_rev\",\"label\":\"Rev\"},{\"key\":\"lt_dly\",\"label\":\"Dly\"}],\"note\":41,\"role\":\"tom\"},\"mt\":{\"na"
    "me\":\"Mid Tom\",\"knobs\":[\"mt_tune\",\"mt_decay\",\"mt_drive\",\"mt_dist_type\",\"mt_level\",\"mt_rev\",\"mt_dly\"],"
    "\"params\":[{\"key\":\"mt_tune\",\"label\":\"Tune\"},{\"key\":\"mt_decay\",\"label\":\"Decay\"},{\"key\":\"mt_drive\",\"lab"
    "el\":\"Drive\"},{\"key\":\"mt_dist_type\",\"label\":\"Distortion\"},{\"key\":\"mt_level\",\"label\":\"Level\"},{\"key\":\""
    "mt_rev\",\"label\":\"Rev\"},{\"key\":\"mt_dly\",\"label\":\"Dly\"}],\"note\":45,\"role\":\"tom\"},\"ht\":{\"name\":\"Hi Tom\""
    ",\"knobs\":[\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht_dist_type\",\"ht_level\",\"ht_rev\",\"ht_dly\"],\"params\":[{\"k"
    "ey\":\"ht_tune\",\"label\":\"Tune\"},{\"key\":\"ht_decay\",\"label\":\"Decay\"},{\"key\":\"ht_drive\",\"label\":\"Drive\"},"
    "{\"key\":\"ht_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ht_level\",\"label\":\"Level\"},{\"key\":\"ht_rev\",\"labe"
    "l\":\"Rev\"},{\"key\":\"ht_dly\",\"label\":\"Dly\"}],\"note\":48,\"role\":\"tom\"},\"lc\":{\"name\":\"Low Conga\",\"knobs\":["
    "\"lc_tune\",\"lc_decay\",\"lc_drive\",\"lc_dist_type\",\"lc_level\",\"lc_rev\",\"lc_dly\"],\"params\":[{\"key\":\"lc_tu"
    "ne\",\"label\":\"Tune\"},{\"key\":\"lc_decay\",\"label\":\"Decay\"},{\"key\":\"lc_drive\",\"label\":\"Drive\"},{\"key\":\"lc"
    "_dist_type\",\"label\":\"Distortion\"},{\"key\":\"lc_level\",\"label\":\"Level\"},{\"key\":\"lc_rev\",\"label\":\"Rev\"},"
    "{\"key\":\"lc_dly\",\"label\":\"Dly\"}],\"note\":64,\"role\":\"conga\"},\"mc\":{\"name\":\"Mid Conga\",\"knobs\":[\"mc_tune"
    "\",\"mc_decay\",\"mc_drive\",\"mc_dist_type\",\"mc_level\",\"mc_rev\",\"mc_dly\"],\"params\":[{\"key\":\"mc_tune\",\"lab"
    "el\":\"Tune\"},{\"key\":\"mc_decay\",\"label\":\"Decay\"},{\"key\":\"mc_drive\",\"label\":\"Drive\"},{\"key\":\"mc_dist_ty"
    "pe\",\"label\":\"Distortion\"},{\"key\":\"mc_level\",\"label\":\"Level\"},{\"key\":\"mc_rev\",\"label\":\"Rev\"},{\"key\":\""
    "mc_dly\",\"label\":\"Dly\"}],\"note\":62,\"role\":\"conga\"},\"hc\":{\"name\":\"Hi Conga\",\"knobs\":[\"hc_tune\",\"hc_dec"
    "ay\",\"hc_drive\",\"hc_dist_type\",\"hc_level\",\"hc_rev\",\"hc_dly\"],\"params\":[{\"key\":\"hc_tune\",\"label\":\"Tune"
    "\"},{\"key\":\"hc_decay\",\"label\":\"Decay\"},{\"key\":\"hc_drive\",\"label\":\"Drive\"},{\"key\":\"hc_dist_type\",\"labe"
    "l\":\"Distortion\"},{\"key\":\"hc_level\",\"label\":\"Level\"},{\"key\":\"hc_rev\",\"label\":\"Rev\"},{\"key\":\"hc_dly\",\""
    "label\":\"Dly\"}],\"note\":63,\"role\":\"conga\"},\"rs\":{\"name\":\"Rim Shot\",\"knobs\":[\"rs_tune\",\"rs_decay\",\"rs_d"
    "rive\",\"rs_dist_type\",\"rs_level\",\"rs_rev\",\"rs_dly\"],\"params\":[{\"key\":\"rs_tune\",\"label\":\"Tune\"},{\"key\""
    ":\"rs_decay\",\"label\":\"Decay\"},{\"key\":\"rs_drive\",\"label\":\"Drive\"},{\"key\":\"rs_dist_type\",\"label\":\"Disto"
    "rtion\"},{\"key\":\"rs_level\",\"label\":\"Level\"},{\"key\":\"rs_rev\",\"label\":\"Rev\"},{\"key\":\"rs_dly\",\"label\":\"D"
    "ly\"}],\"note\":37,\"role\":\"rim\"},\"cl\":{\"name\":\"Claves\",\"knobs\":[\"cl_tune\",\"cl_decay\",\"cl_drive\",\"cl_dis"
    "t_type\",\"cl_level\",\"cl_rev\",\"cl_dly\"],\"params\":[{\"key\":\"cl_tune\",\"label\":\"Tune\"},{\"key\":\"cl_decay\",\""
    "label\":\"Decay\"},{\"key\":\"cl_drive\",\"label\":\"Drive\"},{\"key\":\"cl_dist_type\",\"label\":\"Distortion\"},{\"key"
    "\":\"cl_level\",\"label\":\"Level\"},{\"key\":\"cl_rev\",\"label\":\"Rev\"},{\"key\":\"cl_dly\",\"label\":\"Dly\"}],\"note\":"
    "75,\"role\":\"clave\"},\"ma\":{\"name\":\"Maracas\",\"knobs\":[\"ma_tune\",\"ma_attack\",\"ma_decay\",\"ma_drive\",\"ma_d"
    "ist_type\",\"ma_level\",\"ma_rev\",\"ma_dly\"],\"params\":[{\"key\":\"ma_tune\",\"label\":\"Tune\"},{\"key\":\"ma_attack"
    "\",\"label\":\"Attack\"},{\"key\":\"ma_decay\",\"label\":\"Decay\"},{\"key\":\"ma_drive\",\"label\":\"Drive\"},{\"key\":\"ma"
    "_dist_type\",\"label\":\"Distortion\"},{\"key\":\"ma_level\",\"label\":\"Level\"},{\"key\":\"ma_rev\",\"label\":\"Rev\"},"
    "{\"key\":\"ma_dly\",\"label\":\"Dly\"}],\"note\":70,\"role\":\"shaker\"},\"cp\":{\"name\":\"Hand Clap\",\"knobs\":[\"cp_tun"
    "e\",\"cp_decay\",\"cp_drive\",\"cp_dist_type\",\"cp_level\",\"cp_rev\",\"cp_dly\"],\"params\":[{\"key\":\"cp_tune\",\"la"
    "bel\":\"Tune\"},{\"key\":\"cp_decay\",\"label\":\"Decay\"},{\"key\":\"cp_drive\",\"label\":\"Drive\"},{\"key\":\"cp_dist_t"
    "ype\",\"label\":\"Distortion\"},{\"key\":\"cp_level\",\"label\":\"Level\"},{\"key\":\"cp_rev\",\"label\":\"Rev\"},{\"key\":"
    "\"cp_dly\",\"label\":\"Dly\"}],\"note\":39,\"role\":\"clap\"},\"cb\":{\"name\":\"Cowbell\",\"knobs\":[\"cb_tune\",\"cb_deca"
    "y\",\"cb_drive\",\"cb_dist_type\",\"cb_level\",\"cb_rev\",\"cb_dly\"],\"params\":[{\"key\":\"cb_tune\",\"label\":\"Tune\""
    "},{\"key\":\"cb_decay\",\"label\":\"Decay\"},{\"key\":\"cb_drive\",\"label\":\"Drive\"},{\"key\":\"cb_dist_type\",\"label"
    "\":\"Distortion\"},{\"key\":\"cb_level\",\"label\":\"Level\"},{\"key\":\"cb_rev\",\"label\":\"Rev\"},{\"key\":\"cb_dly\",\"l"
    "abel\":\"Dly\"}],\"note\":56,\"role\":\"cowbell\"},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"ch_tune\",\"ch_decay\",\"c"
    "h_drive\",\"ch_dist_type\",\"ch_level\",\"hh_choke\",\"ch_rev\",\"ch_dly\"],\"params\":[{\"key\":\"ch_tune\",\"label\":"
    "\"Tune\"},{\"key\":\"ch_decay\",\"label\":\"Decay\"},{\"key\":\"ch_drive\",\"label\":\"Drive\"},{\"key\":\"ch_dist_type\","
    "\"label\":\"Distortion\"},{\"key\":\"ch_level\",\"label\":\"Level\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\""
    "ch_rev\",\"label\":\"Rev\"},{\"key\":\"ch_dly\",\"label\":\"Dly\"}],\"note\":42,\"role\":\"hat\"},\"oh\":{\"name\":\"Open Ha"
    "t\",\"knobs\":[\"oh_tune\",\"oh_decay\",\"oh_drive\",\"oh_dist_type\",\"oh_level\",\"oh_rev\",\"oh_dly\"],\"params\":[{"
    "\"key\":\"oh_tune\",\"label\":\"Tune\"},{\"key\":\"oh_decay\",\"label\":\"Decay\"},{\"key\":\"oh_drive\",\"label\":\"Drive\""
    "},{\"key\":\"oh_dist_type\",\"label\":\"Distortion\"},{\"key\":\"oh_level\",\"label\":\"Level\"},{\"key\":\"oh_rev\",\"la"
    "bel\":\"Rev\"},{\"key\":\"oh_dly\",\"label\":\"Dly\"}],\"note\":46,\"role\":\"hat\"},\"cy\":{\"name\":\"Cymbal\",\"knobs\":[\""
    "cy_tune\",\"cy_decay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\",\"cy_rev\",\"cy_dly\"],\"params\":[{\"key\":\"cy_tun"
    "e\",\"label\":\"Tune\"},{\"key\":\"cy_decay\",\"label\":\"Decay\"},{\"key\":\"cy_drive\",\"label\":\"Drive\"},{\"key\":\"cy_"
    "dist_type\",\"label\":\"Distortion\"},{\"key\":\"cy_level\",\"label\":\"Level\"},{\"key\":\"cy_rev\",\"label\":\"Rev\"},{"
    "\"key\":\"cy_dly\",\"label\":\"Dly\"}],\"note\":49,\"role\":\"cymbal\"},\"rev\":{\"name\":\"Reverb\",\"knobs\":[\"rev_decay"
    "\",\"rev_tone\",\"rev_hpf\",\"rev_level\"],\"params\":[{\"key\":\"rev_decay\",\"label\":\"Decay\"},{\"key\":\"rev_tone\","
    "\"label\":\"Tone\"},{\"key\":\"rev_hpf\",\"label\":\"HPF\"},{\"key\":\"rev_level\",\"label\":\"Level\"}]},\"dly\":{\"name\":"
    "\"Delay\",\"knobs\":[\"dly_time\",\"dly_fdbk\",\"dly_tone\",\"dly_hpf\",\"dly_level\"],\"params\":[{\"key\":\"dly_time\""
    ",\"label\":\"Time\"},{\"key\":\"dly_fdbk\",\"label\":\"Fdbk\"},{\"key\":\"dly_tone\",\"label\":\"Tone\"},{\"key\":\"dly_hpf"
    "\",\"label\":\"HPF\"},{\"key\":\"dly_level\",\"label\":\"Level\"}]},\"root\":{\"name\":\"8W8\",\"knobs\":[\"master_dist\",\""
    "master_drive\",\"comp\",\"volume\",\"vel_depth\"],\"params\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd"
    "\",\"label\":\"Snare\"},{\"level\":\"lt\",\"label\":\"Low Tom\"},{\"level\":\"mt\",\"label\":\"Mid Tom\"},{\"level\":\"ht\",\""
    "label\":\"Hi Tom\"},{\"level\":\"lc\",\"label\":\"Low Conga\"},{\"level\":\"mc\",\"label\":\"Mid Conga\"},{\"level\":\"hc\""
    ",\"label\":\"Hi Conga\"},{\"level\":\"rs\",\"label\":\"Rim Shot\"},{\"level\":\"cl\",\"label\":\"Claves\"},{\"level\":\"ma\""
    ",\"label\":\"Maracas\"},{\"level\":\"cp\",\"label\":\"Hand Clap\"},{\"level\":\"cb\",\"label\":\"Cowbell\"},{\"level\":\"ch"
    "\",\"label\":\"Closed Hat\"},{\"level\":\"oh\",\"label\":\"Open Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"level\":\""
    "rev\",\"label\":\"Reverb\"},{\"level\":\"dly\",\"label\":\"Delay\"},{\"key\":\"master_dist\",\"label\":\"Master Dist\"},{"
    "\"key\":\"master_drive\",\"label\":\"Master Drive\"},{\"key\":\"comp\",\"label\":\"Comp\"},{\"key\":\"volume\",\"label\":\""
    "Volume\"},{\"key\":\"vel_depth\",\"label\":\"Velocity\"},{\"key\":\"hh_choke\",\"label\":\"Choke\"},{\"key\":\"note_map\""
    ",\"label\":\"Note Map\"}]}}}";

#endif /* SC808_PARAMS_H */
